-- APR-1:审批留痕表 —— 只记录,不把关,不改变任何行为
--
-- 【为什么它排第一】所有后续切次都需要它,而它不依赖任何东西。Doc 1 要的"谁批的、
-- 谁驳的、谁会签的、什么时候"在今天【没有任何一张表能回答】:三条 HR 链把决定写成
-- 行上的列并【覆盖】它们,所以"驳回 → 重提 → 批准"之后,驳回那一次不留痕迹。
-- 这不是在现有链上补一层报表,而是一张不存在的表。
--
-- 五个决定已定,记在 docs/approvals-scoping.md,后续切次读它不再重问:
--   一级按【角色】路由;二级路由到一个【具名的人】(配置成 user_id,不新建 cfo 角色);
--   阈值放 finance_settings、按【本位币】比、用【单据自己存的汇率】(金额待定);
--   修改把金额抬过阈值 → 原审批作废并重新路由;HR 三条链保留各自的引擎,但【写这张表】。
--
-- ════════════════════════════════════════════════════════════════════════════
-- 【只增不改】pricing_formula_history / employment_history 的形状。守卫【自己报名】,
-- 不靠外键顺带挡住 —— FIN-31 的教训:processing_cost_entries 的硬删此前只是被一条
-- 审计表外键"顺便"拦着,那不是拒绝,只是巧合,而且没有名字。
--
-- 【主体是 (subject_type, subject_id),不是可空外键 XOR】—— 取舍写在
-- docs/approvals-scoping.md,摘要:payment_allocations 的 num_nonnulls XOR 在【四路】
-- 上成立,这里至少六路、将来八路以上,八列里七列恒为 NULL 是一张跟每个新动作打架的表。
-- 外键在【这里】的保护力也弱:主体一律软删(原则 7),本表只增,所以它指的行不会消失。
-- 真实的失误是 subject_type 打错字,而那正好由 CHECK 枚举挡住。
-- 【失去了什么,明写】没有东西阻止 subject_id 指向一行不存在的记录。补偿是
-- 【只有一个写入口】record_approval_decision(),它先核对主体存在再插入,不存在就点名拒绝。
--
-- 【金额冻结在决定当时】单据此后会变(采购单的 estimated_total_ccy 一改明细就动),
-- 而留痕必须能回答"批的时候它值多少",不能回头 join 一个已经变了的数 ——
-- 与 FIN-27 把条款抄到承诺记录上是同一条理由。也正是决定 4(改价抬过阈值就作废重路由)
-- 得以判断的依据:拿新金额跟【冻结的那个】比。
--
-- NOTE: apply with ./db/apply_migration.sh

BEGIN;

CREATE TABLE public.approval_log (
    id                  uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    -- 【留痕需要一个全序,时间戳给不了】decided_at 用 now() = 事务时间,同一个事务里
    -- 的两次决定拿到【同一个】时间戳,于是"先驳回后批准"与"先批准后驳回"在排序上
    -- 分不开 —— 而那正是本表要讲清楚的那件事。seq 是插入顺序的裁决者。
    -- (batch_assay_status 用 code 破同一个平局,理由一样:一个事务里 created_at 相同。)
    seq                 bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY UNIQUE,

    -- ── 主体 ────────────────────────────────────────────────────────────────
    -- 枚举【就是】将来加动作时唯一要改的地方(界面文案的后缀集合也从这里现读,
    -- 与 operations_now.item_type 喂 check-i18n 是同一个做法)。
    subject_type        text NOT NULL CHECK (subject_type IN (
                            'leave_request', 'medical_claim', 'performance_review',
                            'purchase_order', 'payment', 'expense',
                            'pricing_formula', 'stocktake')),
    subject_id          uuid NOT NULL,
    -- 人读的编号,冻结在当时 —— 单据可以改名/作废,留痕不跟着变
    subject_code        text,

    -- ── 决定 ────────────────────────────────────────────────────────────────
    -- countersigned:Doc 1 点名的"会签",【预留取值,本切没有路径写它】——
    -- 与 purchase_orders.approval_status 同一个性质:先把词定下来,免得下一切另起一个。
    -- auto_approved:不是有人做的决定,而是【系统在没有审批流时盖的章】。
    -- 三张既有采购单就是这样来的,回填时用的正是这个值(见文件尾)。
    decision            text NOT NULL CHECK (decision IN (
                            'submitted', 'approved', 'rejected',
                            'acknowledged', 'countersigned', 'auto_approved')),
    -- 1 = 主管,2 = 阈值以上的具名审批人。HR 三条链现在没有层级 → NULL。
    level               smallint CHECK (level IS NULL OR level IN (1, 2)),
    -- 决定人。auth.uid();回填行为 NULL(见 is_reconstructed)。
    actor_user_id       uuid,
    decided_at          timestamptz NOT NULL DEFAULT now(),
    note                text,

    -- ── 金额:冻结在决定当时,全有或全无 ────────────────────────────────────
    -- 【没有金额的主体一律留空,不硬塞】请假的"额度"是【天数】,不是钱,不塞进
    -- 币种列;绩效评估根本没有金额。
    amount_ccy          numeric,
    currency            text REFERENCES public.currencies (code),
    fx_rate             numeric CHECK (fx_rate IS NULL OR fx_rate > 0),
    amount_base         numeric,

    -- ── 回填标记 ────────────────────────────────────────────────────────────
    -- 【重建的事实与当场记下的事实必须分得开】。decided_at/decided_by 是真的记录,
    -- 据它重建终态是【读记录】不是【编事实】;但"完整"是假的 —— 被覆盖掉的驳回
    -- 已经没有了。所以重建行自己说自己是重建的。
    is_reconstructed    boolean NOT NULL DEFAULT false,
    reconstruction_note text,

    created_at          timestamptz NOT NULL DEFAULT now(),

    CONSTRAINT approval_log_amount_shape CHECK (
        (amount_ccy IS NULL AND currency IS NULL AND fx_rate IS NULL AND amount_base IS NULL)
        OR
        (amount_ccy IS NOT NULL AND currency IS NOT NULL AND fx_rate IS NOT NULL AND amount_base IS NOT NULL)
    ),
    CONSTRAINT approval_log_reconstruction_shape CHECK (
        NOT is_reconstructed OR reconstruction_note IS NOT NULL
    )
);

CREATE INDEX idx_approval_log_subject
    ON public.approval_log (subject_type, subject_id, seq);
CREATE INDEX idx_approval_log_actor
    ON public.approval_log (actor_user_id, decided_at DESC);

COMMENT ON TABLE public.approval_log IS
    '审批留痕,只增不改(APR-1)。谁、对什么、做了什么决定、什么时候、当时值多少。三条 HR 链保留各自的引擎但写这里;采购单等动作在 APR-2 起接入。主体是 (subject_type, subject_id) 而非可空外键 XOR —— 取舍与代价见 docs/approvals-scoping.md。';

-- ════════════════════════════════════════════════════════════════════════════
-- 只增不改的守卫。【自己报名】—— 不靠外键顺带挡(FIN-31)。
-- ════════════════════════════════════════════════════════════════════════════
CREATE OR REPLACE FUNCTION public.guard_approval_log_append_only()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
BEGIN
    -- 留痕被改写过,就不是留痕了。两种操作分开报名,免得排查时还要猜是哪一种。
    IF TG_OP = 'UPDATE' THEN
        RAISE EXCEPTION 'APPROVAL_LOG_APPEND_ONLY|update|%', OLD.id;
    ELSE
        RAISE EXCEPTION 'APPROVAL_LOG_APPEND_ONLY|delete|%', OLD.id;
    END IF;
END;
$function$;

CREATE TRIGGER trg_approval_log_append_only
    BEFORE UPDATE OR DELETE ON public.approval_log
    FOR EACH ROW EXECUTE FUNCTION public.guard_approval_log_append_only();

ALTER TABLE public.approval_log ENABLE ROW LEVEL SECURITY;

-- 读:谁看得见留痕。审批史横跨模块,而【读它的人是要审计的人】——
-- 与 auditor 持有全部 module.*.view 是同一条思路:先给读得到相关模块的人。
-- 写:【没有 INSERT 策略】。唯一的写入口是 record_approval_decision()(属主权限),
-- 应用侧任何直接 INSERT 都会被 RLS 挡下 —— 留痕不该有第二个写法。
CREATE POLICY "approval_log select by permission"
    ON public.approval_log
    AS PERMISSIVE FOR SELECT TO authenticated
    USING (
        CASE subject_type
            WHEN 'leave_request'      THEN has_permission('module.hr.view'::text)
            WHEN 'medical_claim'      THEN has_permission('module.hr.view'::text)
            WHEN 'performance_review' THEN has_permission('module.hr.view'::text)
            WHEN 'purchase_order'     THEN has_permission('module.purchasing.view'::text)
            WHEN 'payment'            THEN has_permission('module.finance.view'::text)
            WHEN 'expense'            THEN has_permission('module.finance.view'::text)
            WHEN 'pricing_formula'    THEN has_permission('module.pricing.view'::text)
            WHEN 'stocktake'          THEN has_permission('module.stocktakes.view'::text)
            ELSE false
        END
    );

REVOKE SELECT ON public.approval_log FROM authenticated, anon;
GRANT SELECT (id, seq, subject_type, subject_id, subject_code, decision, level,
              actor_user_id, decided_at, note, amount_ccy, currency, fx_rate,
              amount_base, is_reconstructed, reconstruction_note, created_at)
    ON public.approval_log TO authenticated;

-- ════════════════════════════════════════════════════════════════════════════
-- 唯一的写入口。核对主体存在 → 冻结金额 → 插一行。
-- 【内层函数:不给 authenticated】它没有调用者检查,靠的就是调不到 ——
-- 与 calculate_metal_price_internal 同一个处置,REVOKE 写在
-- db/views/zzz_function_grants.sql 里(那份文件是重建时唯一会跑的授权来源)。
-- ════════════════════════════════════════════════════════════════════════════
CREATE OR REPLACE FUNCTION public.record_approval_decision(
    p_subject_type text,
    p_subject_id   uuid,
    p_decision     text,
    p_level        smallint DEFAULT NULL,
    p_note         text DEFAULT NULL
)
 RETURNS uuid
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public', 'pg_temp'
AS $function$
DECLARE
    v_code text;
    v_ccy  text;
    v_amt  numeric;
    v_rate numeric;
    v_base numeric;
    v_ok   boolean := false;
    v_id   uuid;
    v_base_ccy text;
BEGIN
    SELECT code INTO v_base_ccy FROM currencies WHERE is_base;

    -- 【外键没了,这一段就是它的替代】主体必须真的存在,并且顺手把编号与金额
    -- 冻结下来。不存在 → 点名拒绝,而不是插一行指向空气的留痕。
    CASE p_subject_type
        WHEN 'leave_request' THEN
            -- 请假没有金额:天数不是钱,不塞进币种列
            SELECT true, r.code INTO v_ok, v_code
              FROM leave_requests r WHERE r.id = p_subject_id;
        WHEN 'medical_claim' THEN
            -- amount_sgd 已经是本位币口径(列名是 FIN-0 之前留下的字面量,不是新的判断)
            SELECT true, c.code, c.amount_sgd, v_base_ccy, 1, c.amount_sgd
              INTO v_ok, v_code, v_amt, v_ccy, v_rate, v_base
              FROM medical_claims c WHERE c.id = p_subject_id;
        WHEN 'performance_review' THEN
            SELECT true, e.code INTO v_ok, v_code
              FROM performance_reviews r JOIN employees e ON e.id = r.employee_id
             WHERE r.id = p_subject_id;
        WHEN 'purchase_order' THEN
            -- 【用单据自己存的汇率】(决定 3)—— 审批档次因此不会随行情事后漂移
            SELECT true, po.code, po.estimated_total_ccy, po.currency, po.fx_rate,
                   round(po.estimated_total_ccy * po.fx_rate, 2)
              INTO v_ok, v_code, v_amt, v_ccy, v_rate, v_base
              FROM purchase_orders po WHERE po.id = p_subject_id;
        WHEN 'payment' THEN
            SELECT true, p.code, p.amount_ccy, p.currency, p.fx_rate, p.amount_base
              INTO v_ok, v_code, v_amt, v_ccy, v_rate, v_base
              FROM payments p WHERE p.id = p_subject_id;
        WHEN 'expense' THEN
            SELECT true, e.code, e.amount_ccy, e.currency, e.fx_rate, e.amount_base
              INTO v_ok, v_code, v_amt, v_ccy, v_rate, v_base
              FROM expenses e WHERE e.id = p_subject_id;
        WHEN 'pricing_formula' THEN
            SELECT true, f.code INTO v_ok, v_code
              FROM pricing_formulas f WHERE f.id = p_subject_id;
        WHEN 'stocktake' THEN
            SELECT true, s.code INTO v_ok, v_code
              FROM stocktakes s WHERE s.id = p_subject_id;
        ELSE
            RAISE EXCEPTION 'APPROVAL_SUBJECT_TYPE_UNKNOWN|%', p_subject_type;
    END CASE;

    IF NOT COALESCE(v_ok, false) THEN
        RAISE EXCEPTION 'APPROVAL_SUBJECT_NOT_FOUND|%|%', p_subject_type, p_subject_id;
    END IF;

    INSERT INTO approval_log (subject_type, subject_id, subject_code, decision, level,
                              actor_user_id, note, amount_ccy, currency, fx_rate, amount_base)
    VALUES (p_subject_type, p_subject_id, v_code, p_decision, p_level,
            auth.uid(), p_note, v_amt, v_ccy, v_rate, v_base)
    RETURNING id INTO v_id;

    RETURN v_id;
END;
$function$;

-- ════════════════════════════════════════════════════════════════════════════
-- 三条 HR 链接上留痕。【纯追加】—— 五个函数的签名、判断、返回值一字未动,
-- 只在状态落定之后多插一行。任何一个若非重构不能接,就该报告而不是重构:
-- 实测五个都能,因为它们本来就各自有一个明确的"决定落定"点。
-- 【void_review 没有接】它也是一种决定,但 APR-1 只点名了 submit/approve/acknowledge;
-- 接它同样是纯追加,想接随时可接(记在 docs/approvals-scoping.md)。
-- ════════════════════════════════════════════════════════════════════════════

CREATE OR REPLACE FUNCTION public.decide_leave_request(p_request_id uuid, p_approve boolean, p_notes text DEFAULT NULL::text)
 RETURNS jsonb
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public', 'pg_temp'
AS $function$
DECLARE
    v_req    record;
    v_type   record;
    v_need   numeric;
    v_take   numeric;
    v_bal    jsonb;
    v_avail  numeric;
    v_accrual numeric;
    g        record;
    v_used   jsonb := '[]'::jsonb;
BEGIN
    PERFORM require_permission('module.hr.edit');

    SELECT * INTO v_req FROM leave_requests WHERE id = p_request_id AND deleted_at IS NULL FOR UPDATE;
    IF NOT FOUND THEN RAISE EXCEPTION 'REQUEST_NOT_FOUND'; END IF;
    IF v_req.status <> 'pending' THEN RAISE EXCEPTION 'REQUEST_NOT_PENDING|%', v_req.status; END IF;

    SELECT * INTO v_type FROM leave_types WHERE code = v_req.leave_type_code;

    IF NOT p_approve THEN
        UPDATE leave_requests SET status='rejected', decided_at=now(), decided_by=auth.uid(),
               decision_notes=p_notes, updated_by=auth.uid()
        WHERE id = p_request_id;

        -- APR-1:留痕。【纯追加,不改变本函数任何既有行为】——
        -- 写在状态落定【之后】、返回之前;写失败就整笔回滚(漏记的留痕比出错的留痕更难查)。
        PERFORM record_approval_decision('leave_request', p_request_id, 'rejected', NULL, p_notes);
        RETURN jsonb_build_object('request_id', p_request_id, 'code', v_req.code, 'status','rejected');
    END IF;

    IF v_type.is_accrued THEN
        v_bal := leave_balance(v_req.employee_id, v_req.leave_type_code, v_req.start_date);
        v_avail := (v_bal->>'available')::numeric;
        IF v_avail < v_req.days THEN
            RAISE EXCEPTION 'INSUFFICIENT_ACCRUED_LEAVE|%|%',
                trim_scale(v_avail), trim_scale(v_req.days);
        END IF;

        v_need := v_req.days;
        -- ══════════════════════════════════════════════════════════════════
        -- 【先用旧的】:按 expires_on 从早到晚扣。
        -- 结转来的行有失效日,当年累积没有 —— 所以结转天数天然排在前面被先吃掉,
        -- 反过来的话它们会先烂掉,对员工是净损失。
        -- ══════════════════════════════════════════════════════════════════
        FOR g IN
            SELECT gr.id, gr.days, gr.expires_on, gr.leave_year, gr.grant_type,
                   gr.days
                   - COALESCE((SELECT SUM(CASE WHEN c.entry_type='draw' THEN c.days ELSE -c.days END)
                               FROM leave_consumption c WHERE c.leave_grant_id = gr.id), 0)
                   - COALESCE((SELECT SUM(cf.days) FROM leave_grants cf
                               WHERE cf.source_grant_id = gr.id AND cf.grant_type = 'carry_forward'
                                 AND cf.deleted_at IS NULL), 0) AS remaining
            FROM leave_grants gr
            WHERE gr.employee_id = v_req.employee_id AND gr.leave_type_code = v_req.leave_type_code
              AND gr.deleted_at IS NULL AND gr.granted_on <= v_req.start_date
              AND (gr.expires_on IS NULL OR gr.expires_on >= v_req.start_date)
            ORDER BY gr.expires_on NULLS LAST, gr.granted_on
        LOOP
            EXIT WHEN v_need <= 0;
            IF g.remaining <= 0 THEN CONTINUE; END IF;
            v_take := LEAST(g.remaining, v_need);
            INSERT INTO leave_consumption (leave_request_id, leave_grant_id, entry_type, days)
            VALUES (p_request_id, g.id, 'draw', v_take);
            v_need := v_need - v_take;
            v_used := v_used || jsonb_build_object('source', 'grant', 'grant_id', g.id,
                                                   'leave_year', g.leave_year,
                                                   'grant_type', g.grant_type,
                                                   'expires_on', g.expires_on, 'days', v_take);
        END LOOP;

        -- 结转吃完了还不够 → 从当年度的派生累积里扣(记 accrual_year,不挂授予行)
        IF v_need > 0 AND v_type.is_accrued THEN
            v_accrual := available_annual_accrual(v_req.employee_id, v_req.start_date);
            v_take := LEAST(v_accrual, v_need);
            IF v_take > 0 THEN
                INSERT INTO leave_consumption (leave_request_id, leave_grant_id, entry_type, days, accrual_year)
                VALUES (p_request_id, NULL, 'draw', v_take,
                        EXTRACT(YEAR FROM v_req.start_date)::integer);
                v_need := v_need - v_take;
                v_used := v_used || jsonb_build_object('source', 'accrual',
                                                       'leave_year', EXTRACT(YEAR FROM v_req.start_date)::integer,
                                                       'grant_type', 'monthly_accrual',
                                                       'expires_on', NULL, 'days', v_take);
            END IF;
        END IF;

        IF v_need > 0 THEN
            RAISE EXCEPTION 'INSUFFICIENT_ACCRUED_LEAVE|%|%',
                trim_scale(v_req.days - v_need), trim_scale(v_req.days);
        END IF;
    END IF;

    UPDATE leave_requests SET status='approved', decided_at=now(), decided_by=auth.uid(),
           decision_notes=p_notes, updated_by=auth.uid()
    WHERE id = p_request_id;

    -- APR-1:留痕。【纯追加,不改变本函数任何既有行为】——
    -- 写在状态落定【之后】、返回之前;写失败就整笔回滚(漏记的留痕比出错的留痕更难查)。
    PERFORM record_approval_decision('leave_request', p_request_id, 'approved', NULL, p_notes);

    RETURN jsonb_build_object('request_id', p_request_id, 'code', v_req.code, 'status','approved',
                              'days', v_req.days, 'consumed_from', v_used);
END;
$function$;

CREATE OR REPLACE FUNCTION public.decide_medical_claim(p_claim_id uuid, p_approve boolean, p_notes text DEFAULT NULL::text)
 RETURNS jsonb
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public', 'pg_temp'
AS $function$
DECLARE v_claim record; v_bal jsonb; v_remaining numeric;
BEGIN
    PERFORM require_permission('module.hr.edit');

    SELECT * INTO v_claim FROM medical_claims WHERE id = p_claim_id AND deleted_at IS NULL FOR UPDATE;
    IF NOT FOUND THEN RAISE EXCEPTION 'CLAIM_NOT_FOUND'; END IF;
    IF v_claim.status <> 'submitted' THEN RAISE EXCEPTION 'CLAIM_NOT_SUBMITTED|%', v_claim.status; END IF;

    IF NOT p_approve THEN
        UPDATE medical_claims SET status='rejected', decided_at=now(), decided_by=auth.uid(),
               decision_notes=p_notes, updated_by=auth.uid() WHERE id = p_claim_id;

        -- APR-1:留痕。【纯追加,不改变本函数任何既有行为】——
        -- 写在状态落定【之后】、返回之前;写失败就整笔回滚(漏记的留痕比出错的留痕更难查)。
        PERFORM record_approval_decision('medical_claim', p_claim_id, 'rejected', NULL, p_notes);
        RETURN jsonb_build_object('claim_id', p_claim_id, 'code', v_claim.code, 'status','rejected');
    END IF;

    v_bal := medical_claim_balance(v_claim.employee_id, v_claim.claim_year);
    v_remaining := (v_bal->>'remaining_sgd')::numeric;
    IF v_claim.amount_sgd > v_remaining THEN
        RAISE EXCEPTION 'CLAIM_EXCEEDS_LIMIT|%|%', v_remaining, v_claim.amount_sgd;
    END IF;

    UPDATE medical_claims SET status='approved', decided_at=now(), decided_by=auth.uid(),
           decision_notes=p_notes, updated_by=auth.uid() WHERE id = p_claim_id;

    -- APR-1:留痕。【纯追加,不改变本函数任何既有行为】——
    -- 写在状态落定【之后】、返回之前;写失败就整笔回滚(漏记的留痕比出错的留痕更难查)。
    PERFORM record_approval_decision('medical_claim', p_claim_id, 'approved', NULL, p_notes);

    RETURN jsonb_build_object('claim_id', p_claim_id, 'code', v_claim.code, 'status','approved',
                              'amount_sgd', v_claim.amount_sgd,
                              'remaining_after', v_remaining - v_claim.amount_sgd,
                              -- 与补偿一样,把"没有入账"写进返回值,免得调用方以为记过账了
                              'expense_posted', false,
                              'note', 'No expense is posted. Reimbursement route (payroll vs separate payment) is an operational decision; link it via medical_claims.expense_id once chosen.');
END;
$function$;

CREATE OR REPLACE FUNCTION public.submit_review(p_review_id uuid)
 RETURNS jsonb
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public', 'pg_temp'
AS $function$
DECLARE
    v_r      performance_reviews%ROWTYPE;
    v_goals  integer;
BEGIN
    SELECT * INTO v_r FROM performance_reviews WHERE id = p_review_id FOR UPDATE;
    IF NOT FOUND THEN
        RAISE EXCEPTION 'REVIEW_NOT_FOUND|%', COALESCE(p_review_id::text, '?');
    END IF;

    IF NOT (has_permission('module.hr.edit')
            OR is_reviewer_of(v_r.reviewer_employee_id)) THEN
        RAISE EXCEPTION 'PERMISSION_DENIED|module.hr.edit';
    END IF;

    -- self_review 是可选的一步,所以两个入口状态都收
    IF v_r.status NOT IN ('draft','self_review') THEN
        RAISE EXCEPTION 'REVIEW_BAD_STATUS|%', v_r.status;
    END IF;

    IF v_r.reviewer_employee_id IS NULL THEN
        RAISE EXCEPTION 'REVIEWER_REQUIRED';
    END IF;
    IF v_r.rating_code IS NULL THEN
        RAISE EXCEPTION 'RATING_REQUIRED';
    END IF;
    IF v_r.summary_text IS NULL OR btrim(v_r.summary_text) = '' THEN
        RAISE EXCEPTION 'SUMMARY_REQUIRED';
    END IF;
    IF v_r.review_type = 'probation' AND v_r.probation_outcome IS NULL THEN
        RAISE EXCEPTION 'PROBATION_OUTCOME_REQUIRED';
    END IF;

    SELECT count(*) INTO v_goals FROM review_goals WHERE review_id = p_review_id;
    IF v_goals = 0 THEN
        RAISE EXCEPTION 'GOALS_REQUIRED';
    END IF;

    UPDATE performance_reviews
    SET status = 'submitted', submitted_at = now(), submitted_by = auth.uid()
    WHERE id = p_review_id;

    -- APR-1:留痕。【纯追加,不改变本函数任何既有行为】——
    -- 写在状态落定【之后】、返回之前;写失败就整笔回滚(漏记的留痕比出错的留痕更难查)。
    PERFORM record_approval_decision('performance_review', p_review_id, 'submitted', NULL, NULL);

    RETURN jsonb_build_object('review_id', p_review_id, 'status', 'submitted',
                              'rating_code', v_r.rating_code, 'goals', v_goals);
END;
$function$;

CREATE OR REPLACE FUNCTION public.approve_review(p_review_id uuid)
 RETURNS jsonb
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public', 'pg_temp'
AS $function$
DECLARE
    v_r        performance_reviews%ROWTYPE;
    v_emp      employees%ROWTYPE;
    v_period   text;
    v_old_sal  numeric;
    v_conf     date;
    v_confirmed boolean := false;
    v_salaried  boolean := false;
BEGIN
    PERFORM require_permission('module.hr.edit');

    SELECT * INTO v_r FROM performance_reviews WHERE id = p_review_id FOR UPDATE;
    IF NOT FOUND THEN
        RAISE EXCEPTION 'REVIEW_NOT_FOUND|%', COALESCE(p_review_id::text, '?');
    END IF;
    IF v_r.status <> 'submitted' THEN
        RAISE EXCEPTION 'REVIEW_BAD_STATUS|%', v_r.status;
    END IF;

    -- 【提交人不能自批】四眼原则。与"评估人不能是本人"是两条不同的规则:
    -- 一条防自我评价,这一条防自我批准。
    IF v_r.submitted_by IS NOT NULL AND v_r.submitted_by = auth.uid() THEN
        RAISE EXCEPTION 'SELF_APPROVAL_FORBIDDEN';
    END IF;

    SELECT * INTO v_emp FROM employees WHERE id = v_r.employee_id FOR UPDATE;
    IF NOT FOUND THEN RAISE EXCEPTION 'EMPLOYEE_NOT_FOUND'; END IF;

    UPDATE performance_reviews
    SET status = 'approved', approved_at = now(), approved_by = auth.uid()
    WHERE id = p_review_id;

    -- APR-1:留痕。【纯追加,不改变本函数任何既有行为】——
    -- 写在状态落定【之后】、返回之前;写失败就整笔回滚(漏记的留痕比出错的留痕更难查)。
    PERFORM record_approval_decision('performance_review', p_review_id, 'approved', NULL, NULL);

    -- ── 试用期转正 ────────────────────────────────────────────────────────
    IF v_r.review_type = 'probation' AND v_r.probation_outcome = 'confirm' THEN
        IF v_emp.employment_status = 'separated' THEN
            RAISE EXCEPTION 'EMPLOYEE_SEPARATED|%', v_emp.code;
        END IF;
        v_conf := COALESCE(v_emp.probation_end_date, CURRENT_DATE);

        UPDATE employees
        SET employment_status = 'active',      -- 【没有 'confirmed' 这个状态,见文件头 (2)】
            confirmation_date = v_conf
        WHERE id = v_emp.id;

        -- 【恰好一行】履历。
        INSERT INTO employment_history
            (employee_id, effective_date, change_type, job_title, department_id,
             employment_type, employment_status, notes)
        VALUES (v_emp.id, v_conf, 'confirmed', v_emp.job_title, v_emp.department_id,
                v_emp.employment_type, 'active',
                format('Probation confirmed by performance review %s', p_review_id));

        -- 【假期台账一个字都不写】年假的解锁是读时按 employment_status 派生的
        -- (submit_leave_request 的 PROBATION_NO_ANNUAL_LEAVE)。在这里补一笔授予
        -- 就是 HR-2a 结转重复计数的翻版。见文件头 (1)。
        v_confirmed := true;
    END IF;

    -- ── 不予转正:【什么都不改】 ──────────────────────────────────────────
    -- 决定记在评估单据上,提醒由 hr_alerts 的 probation_not_confirmed 一支发出。
    -- 【绝不把在职状态改成 separated,也绝不触发任何离职逻辑】——
    -- 离职是手工流程:人一旦 separated 就掉出工资表,而最后一个月的工资还没录。
    -- 先掉出去,那笔钱就再也发不出来了。

    -- ── 调薪 ──────────────────────────────────────────────────────────────
    IF v_r.new_monthly_salary IS NOT NULL THEN
        -- payroll_periods 没有起止两列:周期就是 period_month 那个整月(见文件头 (4))
        SELECT p.code INTO v_period
        FROM payroll_periods p
        WHERE p.deleted_at IS NULL AND p.status = 'posted'
          AND v_r.salary_effective_date >= p.period_month
          AND v_r.salary_effective_date < (p.period_month + interval '1 month')::date
        ORDER BY p.period_month
        LIMIT 1;

        IF v_period IS NOT NULL THEN
            -- 【连同上面的转正一起回滚】总账已经认了那个月的工资,
            -- 追改一个已过账周期里的薪酬会让账实不符。
            RAISE EXCEPTION 'SALARY_EFFECTIVE_IN_POSTED_PERIOD|%', v_period;
        END IF;

        v_old_sal := v_emp.monthly_salary;

        UPDATE employees SET monthly_salary = v_r.new_monthly_salary WHERE id = v_emp.id;

        INSERT INTO employment_history
            (employee_id, effective_date, change_type, job_title, department_id,
             employment_type, employment_status, old_monthly_salary, new_monthly_salary, notes)
        SELECT e.id, v_r.salary_effective_date, 'salary_change', e.job_title, e.department_id,
               e.employment_type, e.employment_status, v_old_sal, v_r.new_monthly_salary,
               format('Salary change approved with performance review %s', p_review_id)
        FROM employees e WHERE e.id = v_emp.id;

        v_salaried := true;
    END IF;

    RETURN jsonb_build_object(
        'review_id', p_review_id, 'status', 'approved',
        'employee_code', v_emp.code,
        'review_type', v_r.review_type,
        'probation_outcome', v_r.probation_outcome,
        'confirmed', v_confirmed,
        'confirmation_date', v_conf,
        'salary_changed', v_salaried,
        'old_monthly_salary', v_old_sal,
        'new_monthly_salary', v_r.new_monthly_salary,
        'salary_effective_date', v_r.salary_effective_date);
END;
$function$;

CREATE OR REPLACE FUNCTION public.acknowledge_review(p_review_id uuid)
 RETURNS jsonb
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public', 'pg_temp'
AS $function$
DECLARE
    v_r performance_reviews%ROWTYPE;
BEGIN
    SELECT * INTO v_r FROM performance_reviews WHERE id = p_review_id FOR UPDATE;
    IF NOT FOUND THEN
        RAISE EXCEPTION 'REVIEW_NOT_FOUND|%', COALESCE(p_review_id::text, '?');
    END IF;

    IF v_r.employee_id IS DISTINCT FROM current_user_employee() THEN
        RAISE EXCEPTION 'NOT_REVIEW_SUBJECT';
    END IF;

    IF v_r.status <> 'approved' THEN
        RAISE EXCEPTION 'REVIEW_BAD_STATUS|%', v_r.status;
    END IF;

    UPDATE performance_reviews
    SET status = 'acknowledged', acknowledged_at = now()
    WHERE id = p_review_id;

    -- APR-1:留痕。【纯追加,不改变本函数任何既有行为】——
    -- 写在状态落定【之后】、返回之前;写失败就整笔回滚(漏记的留痕比出错的留痕更难查)。
    PERFORM record_approval_decision('performance_review', p_review_id, 'acknowledged', NULL, NULL);

    RETURN jsonb_build_object('review_id', p_review_id, 'status', 'acknowledged');
END;
$function$;

-- ════════════════════════════════════════════════════════════════════════════
-- 回填:三张既有采购单。
--
-- 【为什么是 auto_approved 而不是 approved】create_purchase_order 在没有审批流的情况下
-- 无条件盖章(表镜像原话:"结构在此,流程不在此"),所以那三行【不是谁做的决定】。
-- 记成 approved 会凭空造出一个决定 —— FIN-26 的规矩:编造的出处比空白更坏,
-- pricing_formula_history 当初也正是据此拒绝回填。
-- 【那为什么不干脆不记】因为采购单页面上明明白白写着 approved,而留痕里一片空白 ——
-- 读的人会得出"留痕坏了"的结论。记下【真实发生的那件事】(系统盖的章,没有人决定),
-- 并标成重建,才是既不编造也不沉默。
--
-- 【三条 HR 链没有回填,因为无可回填】live 上 leave_requests / medical_claims /
-- performance_reviews 【一行都没有】(不是被覆盖了,是从没走过)。
-- ════════════════════════════════════════════════════════════════════════════
INSERT INTO approval_log (subject_type, subject_id, subject_code, decision, level,
                          actor_user_id, decided_at, note,
                          amount_ccy, currency, fx_rate, amount_base,
                          is_reconstructed, reconstruction_note)
SELECT 'purchase_order', po.id, po.code, 'auto_approved', NULL,
       po.approved_by, po.approved_at,
       NULL,
       po.estimated_total_ccy, po.currency, po.fx_rate,
       round(po.estimated_total_ccy * po.fx_rate, 2),
       true,
       'APR-1 回填。create_purchase_order 在审批流存在之前无条件盖章:approved_at/approved_by 是真实记录的事实,但它们记的是【系统盖章】,不是有人做的决定 —— 故 decision = auto_approved。金额按单据自己存的汇率折本位币冻结于此。'
FROM purchase_orders po
WHERE po.approved_at IS NOT NULL;

COMMIT;
