// lib/trail/text.ts
// ════════════════════════════════════════════════════════════════════════════
// AUDIT-TRAIL-1a(Tim 的 Q7 · Q9 · Q10 · Q17 · Q18)· 审计记录的【英文措辞目录】—— 一份,英文专用
// ════════════════════════════════════════════════════════════════════════════
// 【为什么不在 messages/en.ts 里】审计记录只说英文,界面是中文时也一样(Q7)。放进 en.ts,check-i18n 会要求
//   zh.ts 里有同一个键的中文 —— 那正是 Tim 不要的东西。所以它自成一份,由 scripts/check-trail-wording.mjs
//   管它的完整性:代码里用到的每一个键都在这里、这里的每一个键都有人用、每一句都过机器字检查。
// 【措辞的出处】§4 的表(Tim 确认,Q9)照录;其余是本刀为三个主语补的,交回报告逐条列出给 Tim 过目。
// 【一个 import 都没有】理由同 lib/dates.ts 的决定 ①。
// {x} 是占位,由 lib/trail/render.ts 的 fill() 填 —— 填进去的永远是已经解析成人话的值,不是代码。
export const TRAIL_TEXT = {
    // ── 版式(Q27)────────────────────────────────────────────────────────────
    'section.title': 'Audit trail',
    'section.intro': 'Newest first · Singapore time',
    'col.when': 'When',
    'col.who': 'Who',
    'col.what': 'What happened',
    'col.record': 'Record',
    'restricted': 'Restricted',
    'empty': '(empty)',
    'showMore': 'Show {n} more',
    'showLess': 'Show less',
    'more': 'more',
    'less': 'less',
    'olderEntries': 'Show older entries',
    'noEntries': 'Nothing has been recorded for this record yet.',
    'divider': 'Before {date}, only key steps and amendments were kept; single-field edits were not.',
    'reason': 'Reason',
    'restrictedPart': 'Part of this change is restricted.',
    'refusal.notPermitted': 'You cannot see the audit trail of this record.',
    'refusal.unknown': 'This page does not have an audit trail yet.',
    // ── 谁(Q14 · Q17 · Q18)───────────────────────────────────────────────────
    'who.system': 'System (automatic)',
    'who.removed': 'Removed account',
    'who.unlinked': 'An account with no person linked',
    'who.anonymised': 'A former employee',
    'who.unknown': 'Not recorded',
    // ── 值(Q12 · Q13)─────────────────────────────────────────────────────────
    'value.yes': 'Yes',
    'value.no': 'No',
    'value.sinceDeleted': '{label} (since deleted)',
    'value.goneGeneric': 'a {thing} that has since been deleted',
    'value.unnamed': 'a {thing}',
    'value.detailsChanged': 'Details changed',
    'value.detailsRecorded': 'Details recorded',
    // ── 通用(任何一张没有专门措辞的表;Q9 的 K01–K04)──────────────────────────
    'generic.created': '{Thing} created',
    'generic.edited': '{Thing} edited',
    'generic.deleted': '{Thing} deleted',
    'generic.truncated': 'Every {thing} record removed at once',
    // ── 账号事件(HISTORY-1 §6)────────────────────────────────────────────────
    'account.ACCOUNT_CREATE': 'Account created',
    'account.ACCOUNT_DELETE': 'Account removed (it was never finished)',
    'account.ACCOUNT_DISABLE': 'Account disabled',
    'account.ACCOUNT_DISABLE_FAILED': 'Account could not be disabled',
    'account.ACCOUNT_ENABLE': 'Account re-enabled',
    'account.ACCOUNT_ENABLE_FAILED': 'Account could not be re-enabled',
    // ── 采购单(§4 的表 + A01–A22)────────────────────────────────────────────
    'po.raised': 'Purchase order raised',
    'po.raisedPending': 'Purchase order raised — waiting for approval',
    'po.lines.one': '{n} line',
    'po.lines.many': '{n} lines',
    'po.autoApproved': 'Approved automatically (approvals were switched off)',
    'po.submitted': 'Submitted for approval',
    'po.approved': 'Purchase order approved',
    'po.approvedLevel': 'Purchase order approved (level {level})',
    'po.rejected': 'Purchase order rejected',
    'po.approvalVoided': 'Approval withdrawn — the order value went up',
    'po.approvalOther': 'Approval step recorded: {decision}',
    'po.firstReceipt': 'First goods received — order now receiving',
    'po.closed': 'Purchase order closed',
    'po.reopened': 'Purchase order reopened',
    'po.cancelled': 'Purchase order cancelled',
    'po.deleted': 'Purchase order deleted',
    'po.statusChanged': 'Purchase order status changed',
    'po.amended': 'Purchase order amended',
    'po.changes.one': '{n} change',
    'po.changes.many': '{n} changes',
    'po.edited': 'Purchase order edited',
    'po.issued': 'Purchase order issued to the supplier (version {version})',
    'po.lineHeading': 'Line {n}',
    'po.lineAdded': 'Line added',
    'po.lineChanged': 'Line changed',
    'po.lineRemoved': 'Line removed',
    'po.termHeading': 'Instalment {n}',
    'po.termAdded': 'Instalment added',
    'po.termChanged': 'Instalment changed',
    'po.termRemoved': 'Instalment removed',
    'po.dueDateSet': 'Instalment due date set',
    'po.retentionSet': 'Retention set',
    'po.retentionReleased': 'Retention released',
    'po.retentionChanged': 'Retention changed',
    'po.termsCommitted': 'Pricing terms committed',
    'po.contractLinked': 'Linked to contract {code}',
    'po.contractLinkedPlain': 'Linked to a contract',
    // ── 加工单(Q10 · B14–B21)───────────────────────────────────────────────
    'run.completed': 'Processing completed',
    'run.processDate': 'process date {date}',
    'run.used': 'Used',
    'run.produced': 'Produced',
    'run.loss': 'Loss',
    'run.allocated': 'Processing costs allocated',
    'run.capitalised': 'Capitalised',
    'run.journal': 'Journal',
    'run.rolledBack': 'Processing rolled back',
    'run.edited': 'Processing record edited',
    'run.basisChanged': 'Cost allocation basis changed',
    'run.costAdded': 'Processing cost added',
    'run.costChanged': 'Processing cost changed',
    'run.costRemoved': 'Processing cost removed',
    'run.costRestored': 'Processing cost restored',
    'run.costRelieved': 'Accrued cost relieved by a real invoice',
    'run.estimate': '(estimate)',
    'run.lossRecorded': 'Loss recorded',
    'run.lossChanged': 'Loss changed',
    'run.lossRemoved': 'Loss removed',
    'run.batchShare': 'Cost share',
    // ── 角色(I01 · I02 · I11)──────────────────────────────────────────────
    'role.created': 'Role created',
    'role.edited': 'Role edited',
    'role.deactivated': 'Role deactivated',
    'role.reactivated': 'Role reactivated',
    'role.deleted': 'Role deleted',
    'role.permsChanged': 'Permissions changed',
    'role.permsSet': 'Permissions set',
    'role.added': '{n} added',
    'role.removed': '{n} removed',
    'role.perms.one': '{n} permission',
    'role.perms.many': '{n} permissions',
    'role.lineAdded': 'Added',
    'role.lineRemoved': 'Removed',
    'role.lineGiven': 'Given',
    'role.notKept': 'The list before this was not kept.',
    // ── 汇总页的内容部分(Q30:与审计记录同一种说法)───────────────────────────
    'summary.noRecord': 'Not tied to a single record',
    'summary.keyHidden.one': 'Key events only — {n} routine edit on this page is hidden.',
    'summary.keyHidden.many': 'Key events only — {n} routine edits on this page are hidden.',
    // ════ AUDIT-TRAIL-1b-1(Tim 2026-09-29)────────────────────────────────────────
    // ── 折入 3:审计记录那一段里的每一个字都是英文(读屏的"changed to"与汇总页的空状态、分页说明)──
    'srChangedTo': 'changed to',
    'summary.empty': 'No changes match these filters.',
    'summary.noRecordMatch': 'No record matches “{q}”.',
    'summary.pageNote': 'Newest first · Singapore time · {n} operations shown',
    // ── /inventory 的仓库申请那一块(Q12)──────────────────────────────────────
    'wrBlock.intro': 'Recent warehouse requests · newest first · Singapore time',
    'wrBlock.empty': 'No warehouse request has been recorded yet.',
    // ── 结束了的记录(Q21 · Q8):页头的横幅,第二行是理由 ─────────────────────────
    'banner.writtenOff': 'Written off on {date} by {who}',
    'banner.writtenOffDate': 'Written off on {date}',
    'banner.reversed': 'Reversed on {date} by {who}',
    'banner.reversedDate': 'Reversed on {date}',
    // ── 批次(进料 / 产出)─────────────────────────────────────────────────────
    'batch.received': 'Goods received',
    'batch.outputCreated': 'Output batch created',
    'batch.writtenOff': 'Batch written off',
    'batch.edited': 'Batch details changed',
    'batch.stageStarted': 'Processing started on this batch',
    'batch.stageDone': 'Fully processed',
    'batch.stageBack': 'Returned to stock to process (processing rolled back)',
    'batch.permitVerified': 'Import permit verified',
    'batch.sourceReason': 'Source reason recorded',
    'batch.priceFinal': 'Receipt price finalised',
    'batch.noPurchaseOrder': 'Not received against a purchase order',
    'batch.noCogs': 'No cost-of-sales journal',
    'batch.runRolledBack': 'This processing was later rolled back',
    'batch.movement': 'Stock movement · {type}',
    'batch.priceChanged': 'Price changed',
    'batch.usedIn': 'Used in processing {run}',
    'batch.producedBy': 'Produced by processing {run}',
    'batch.costFrom': 'Processing cost allocated from {run}',
    'batch.useChanged': 'Processing record for this batch changed',
    'batch.metalRecorded': 'Metal content recorded',
    'batch.metalsChanged': 'Metal content changed',
    'batch.metalRemoved': 'Metal content removed',
    'batch.assayRecorded': 'Assay recorded',
    'batch.assayApplied': 'Assay applied to this batch',
    'batch.assayWithdrawn': 'Assay result withdrawn',
    'batch.assayDeleted': 'Assay deleted',
    'batch.assayChanged': 'Assay changed',
    'batch.safetyAdded': 'Safety state recorded',
    'batch.safetyRemoved': 'Safety state removed',
    'batch.priceRequested': 'Receipt price request raised',
    'batch.priceRequestWithdrawn': 'Receipt price request withdrawn',
    'batch.priceRequestChanged': 'Receipt price request updated',
    'batch.prepayment': 'Prepayment applied',
    'batch.freight': 'Freight cost allocated',
    'batch.payment': 'Payment allocated',
    'batch.attachmentAdded': 'Attachment added',
    'batch.attachmentRemoved': 'Attachment removed',
    'batch.codIssued': 'Certificate of destruction issued',
    'batch.codPending': 'Certificate of destruction prepared — not issued yet',
    'batch.codVoided': 'Certificate of destruction voided',
    'batch.codChanged': 'Certificate of destruction updated',
    'batch.codPdf': 'Certificate of destruction PDF issued',
    'batch.sold': 'Sold',
    'batch.saleChanged': 'Sale changed',
    'batch.saleStock': 'Stock issued for the sale',
    'batch.saleAttributed': 'Sale attributed',
    'batch.invoiced': 'Invoiced',
    'batch.reserved': 'Reserved for a sales order',
    'batch.reservationReleased': 'Reservation released',
    'batch.reservationUsed': 'Reservation used by a shipment',
    'batch.shipped': 'Shipped',
    'batch.reportIssued': 'Traceability report issued',
    'batch.settlement': 'Sales settlement calculated',
    'batch.counted': 'Counted in stocktake {code}',
    // ── 分录 ─────────────────────────────────────────────────────────────────
    'journal.posted': 'Journal posted · {code}',
    'journal.reversal': 'Reversal journal posted · {code}',
    'journal.reversedBy': 'Journal {code} reversed by {by}',
    'journal.laterReversed': 'Later reversed by {by}',
    'journal.edited': 'Journal changed',
    // ── 审批(任何一种单据;{thing} 是单据类型与它的编号)───────────────────────
    'approval.submitted': '{Thing} submitted for approval',
    'approval.approved': '{Thing} approved',
    'approval.approvedLevel': '{Thing} approved (level {level})',
    'approval.rejected': '{Thing} rejected',
    'approval.auto': '{Thing} approved automatically (approvals were switched off)',
    'approval.other': '{Thing}: approval step recorded — {decision}',
    // ── 工单 ─────────────────────────────────────────────────────────────────
    'wo.created': 'Work order created',
    'wo.released': 'Work order released',
    'wo.closed': 'Work order closed',
    'wo.cancelled': 'Work order cancelled',
    'wo.amended': 'Work order amended',
    'wo.edited': 'Work order edited',
    'wo.lineAdded': 'Input line added',
    'wo.lineChanged': 'Input line changed',
    'wo.lineRemoved': 'Input line removed',
    'wo.expectedAdded': 'Expected output added',
    'wo.expectedChanged': 'Expected output changed',
    'wo.expectedRemoved': 'Expected output removed',
    // ── 盘点 ─────────────────────────────────────────────────────────────────
    'st.started': 'Stocktake started',
    'st.posted': 'Stocktake posted',
    'st.cancelled': 'Stocktake cancelled',
    'st.edited': 'Stocktake edited',
    'st.count': 'Count recorded',
    'st.recount': 'Count changed',
    'st.lineRemoved': 'Count removed',
    // ── 设备 ─────────────────────────────────────────────────────────────────
    'eq.cardCreated': 'Asset card created',
    'eq.cardEdited': 'Asset card edited',
    'eq.service': 'Service recorded',
    'eq.repair': 'Repair recorded',
    'eq.workChanged': 'Service record changed',
    'eq.workRemoved': 'Service record removed',
    'eq.capitalised': 'Work capitalised',
    'eq.down': 'Downtime started',
    'eq.up': 'Downtime ended',
    'eq.downChanged': 'Downtime changed',
    'eq.intervalSet': 'Service interval set',
    'eq.intervalChanged': 'Service interval changed',
    'eq.intervalRemoved': 'Service interval removed',
    'eq.handoverNote': 'Mentioned in a shift handover',
    // ── 交接班 ───────────────────────────────────────────────────────────────
    'ho.submitted': 'Shift handover submitted',
    'ho.acknowledged': 'Shift handover acknowledged',
    'ho.edited': 'Shift handover edited',
    'ho.item': 'Handover item added',
    'ho.downtime': 'Downtime noted in the handover',
    // ── 仓库申请 ─────────────────────────────────────────────────────────────
    'wr.raised': '{Kind} requested',
    'wr.approved': '{Kind} request approved and carried out',
    'wr.rejected': '{Kind} request rejected',
    'wr.withdrawn': '{Kind} request withdrawn',
    'wr.changed': '{Kind} request updated',
    'wr.kind.writeOff': 'write-off',
    'wr.kind.rollback': 'processing rollback',
    'wr.kind.codVoid': 'certificate void',
    'wr.kind.other': 'warehouse',
    // ── 销售订单的修改(产出批次页上,它的销售对应的那一行)──────────────────────
    'so.changed': 'Sales order changed',
} as const

export type TrailTextKey = keyof typeof TRAIL_TEXT
export type TrailText = typeof TRAIL_TEXT
