// lib/trail/text.ts
// ════════════════════════════════════════════════════════════════════════════
// AUDIT-TRAIL-1a(Tim 的 Q7 · Q9 · Q10 · Q17 · Q18)· 审计记录的【英文措辞目录】—— 一份,英文专用
// ════════════════════════════════════════════════════════════════════════════
// 【为什么不在 messages/en.ts 里】审计记录只说英文,界面是中文时也一样(Q7)。放进 en.ts,check-i18n 会要求
//   zh.ts 里有同一个键的中文 —— 那正是 Tim 不要的东西。所以它自成一份,由 scripts/check-trail-wording.mjs
//   管它的完整性:代码里用到的每一个键都在这里、这里的每一个键都有人用、每一句都过机器字检查。
// 【措辞的出处】§4 的表(Tim 确认,Q9)照录;其余是本刀为三个主语补的,交回报告逐条列出给 Tim 过目。
// 【一个 import 都没有】理由同 lib/dates.ts 的决定 ①。
// {x} 是占位,由 lib/trail/render.ts 的 fill() 填 —— 填进去的永远是已经解析成人话的值,不是代码。
export const TRAIL_TEXT = {
    // ── 版式(Q27)────────────────────────────────────────────────────────────
    'section.title': 'Audit trail',
    'section.intro': 'Newest first · Singapore time',
    'col.when': 'When',
    'col.who': 'Who',
    'col.what': 'What happened',
    'col.record': 'Record',
    'restricted': 'Restricted',
    'empty': '(empty)',
    'showMore': 'Show {n} more',
    'showLess': 'Show less',
    'more': 'more',
    'less': 'less',
    'olderEntries': 'Show older entries',
    'noEntries': 'Nothing has been recorded for this record yet.',
    'divider': 'Before {date}, only key steps and amendments were kept; single-field edits were not.',
    'reason': 'Reason',
    'restrictedPart': 'Part of this change is restricted.',
    'refusal.notPermitted': 'You cannot see the audit trail of this record.',
    'refusal.unknown': 'This page does not have an audit trail yet.',
    // ── 谁(Q14 · Q17 · Q18)───────────────────────────────────────────────────
    'who.system': 'System (automatic)',
    'who.removed': 'Removed account',
    'who.unlinked': 'An account with no person linked',
    'who.anonymised': 'A former employee',
    'who.unknown': 'Not recorded',
    // ── 值(Q12 · Q13)─────────────────────────────────────────────────────────
    'value.yes': 'Yes',
    'value.no': 'No',
    'value.sinceDeleted': '{label} (since deleted)',
    'value.goneGeneric': 'a {thing} that has since been deleted',
    'value.unnamed': 'a {thing}',
    'value.detailsChanged': 'Details changed',
    'value.detailsRecorded': 'Details recorded',
    // ── 通用(任何一张没有专门措辞的表;Q9 的 K01–K04)──────────────────────────
    'generic.created': '{Thing} created',
    'generic.edited': '{Thing} edited',
    'generic.deleted': '{Thing} deleted',
    'generic.truncated': 'Every {thing} record removed at once',
    // ── 账号事件(HISTORY-1 §6)────────────────────────────────────────────────
    'account.ACCOUNT_CREATE': 'Account created',
    'account.ACCOUNT_DELETE': 'Account removed (it was never finished)',
    'account.ACCOUNT_DISABLE': 'Account disabled',
    'account.ACCOUNT_DISABLE_FAILED': 'Account could not be disabled',
    'account.ACCOUNT_ENABLE': 'Account re-enabled',
    'account.ACCOUNT_ENABLE_FAILED': 'Account could not be re-enabled',
    // ── 采购单(§4 的表 + A01–A22)────────────────────────────────────────────
    'po.raised': 'Purchase order raised',
    'po.raisedPending': 'Purchase order raised — waiting for approval',
    'po.lines.one': '{n} line',
    'po.lines.many': '{n} lines',
    'po.autoApproved': 'Approved automatically (approvals were switched off)',
    'po.submitted': 'Submitted for approval',
    'po.approved': 'Purchase order approved',
    'po.approvedLevel': 'Purchase order approved (level {level})',
    'po.rejected': 'Purchase order rejected',
    'po.approvalVoided': 'Approval withdrawn — the order value went up',
    'po.approvalOther': 'Approval step recorded: {decision}',
    'po.firstReceipt': 'First goods received — order now receiving',
    'po.closed': 'Purchase order closed',
    'po.reopened': 'Purchase order reopened',
    'po.cancelled': 'Purchase order cancelled',
    'po.deleted': 'Purchase order deleted',
    'po.statusChanged': 'Purchase order status changed',
    'po.amended': 'Purchase order amended',
    'po.changes.one': '{n} change',
    'po.changes.many': '{n} changes',
    'po.edited': 'Purchase order edited',
    'po.issued': 'Purchase order issued to the supplier (version {version})',
    'po.lineHeading': 'Line {n}',
    'po.lineAdded': 'Line added',
    'po.lineChanged': 'Line changed',
    'po.lineRemoved': 'Line removed',
    'po.termHeading': 'Instalment {n}',
    'po.termAdded': 'Instalment added',
    'po.termChanged': 'Instalment changed',
    'po.termRemoved': 'Instalment removed',
    'po.dueDateSet': 'Instalment due date set',
    'po.retentionSet': 'Retention set',
    'po.retentionReleased': 'Retention released',
    'po.retentionChanged': 'Retention changed',
    'po.termsCommitted': 'Pricing terms committed',
    'po.contractLinked': 'Linked to contract {code}',
    'po.contractLinkedPlain': 'Linked to a contract',
    // ── 加工单(Q10 · B14–B21)───────────────────────────────────────────────
    'run.completed': 'Processing completed',
    'run.processDate': 'process date {date}',
    'run.used': 'Used',
    'run.produced': 'Produced',
    'run.loss': 'Loss',
    'run.allocated': 'Processing costs allocated',
    'run.capitalised': 'Capitalised',
    'run.journal': 'Journal',
    'run.rolledBack': 'Processing rolled back',
    'run.edited': 'Processing record edited',
    'run.basisChanged': 'Cost allocation basis changed',
    'run.costAdded': 'Processing cost added',
    'run.costChanged': 'Processing cost changed',
    'run.costRemoved': 'Processing cost removed',
    'run.costRestored': 'Processing cost restored',
    'run.costRelieved': 'Accrued cost relieved by a real invoice',
    'run.estimate': '(estimate)',
    'run.lossRecorded': 'Loss recorded',
    'run.lossChanged': 'Loss changed',
    'run.lossRemoved': 'Loss removed',
    'run.batchShare': 'Cost share',
    // ── 角色(I01 · I02 · I11)──────────────────────────────────────────────
    'role.created': 'Role created',
    'role.edited': 'Role edited',
    'role.deactivated': 'Role deactivated',
    'role.reactivated': 'Role reactivated',
    'role.deleted': 'Role deleted',
    'role.permsChanged': 'Permissions changed',
    'role.permsSet': 'Permissions set',
    'role.added': '{n} added',
    'role.removed': '{n} removed',
    'role.perms.one': '{n} permission',
    'role.perms.many': '{n} permissions',
    'role.lineAdded': 'Added',
    'role.lineRemoved': 'Removed',
    'role.lineGiven': 'Given',
    'role.notKept': 'The list before this was not kept.',
    // ── 汇总页的内容部分(Q30:与审计记录同一种说法)───────────────────────────
    'summary.noRecord': 'Not tied to a single record',
    'summary.keyHidden.one': 'Key events only — {n} routine edit on this page is hidden.',
    'summary.keyHidden.many': 'Key events only — {n} routine edits on this page are hidden.',
    // ════ AUDIT-TRAIL-1b-1(Tim 2026-09-29)────────────────────────────────────────
    // ── 折入 3:审计记录那一段里的每一个字都是英文(读屏的"changed to"与汇总页的空状态、分页说明)──
    'srChangedTo': 'changed to',
    'summary.empty': 'No changes match these filters.',
    'summary.noRecordMatch': 'No record matches “{q}”.',
    'summary.pageNote': 'Newest first · Singapore time · {n} operations shown',
    // ── /inventory 的仓库申请那一块(Q12)──────────────────────────────────────
    'wrBlock.intro': 'Recent warehouse requests · newest first · Singapore time',
    'wrBlock.empty': 'No warehouse request has been recorded yet.',
    // ── 结束了的记录(Q21 · Q8):页头的横幅,第二行是理由 ─────────────────────────
    'banner.writtenOff': 'Written off on {date} by {who}',
    'banner.writtenOffDate': 'Written off on {date}',
    'banner.reversed': 'Reversed on {date} by {who}',
    'banner.reversedDate': 'Reversed on {date}',
    // ── 批次(进料 / 产出)─────────────────────────────────────────────────────
    'batch.received': 'Goods received',
    'batch.outputCreated': 'Output batch created',
    'batch.writtenOff': 'Batch written off',
    'batch.edited': 'Batch details changed',
    'batch.stageStarted': 'Processing started on this batch',
    'batch.stageDone': 'Fully processed',
    'batch.stageBack': 'Returned to stock to process (processing rolled back)',
    'batch.permitVerified': 'Import permit verified',
    'batch.sourceReason': 'Source reason recorded',
    'batch.priceFinal': 'Receipt price finalised',
    'batch.noPurchaseOrder': 'Not received against a purchase order',
    'batch.noCogs': 'No cost-of-sales journal',
    'batch.runRolledBack': 'This processing was later rolled back',
    'batch.movement': 'Stock movement · {type}',
    'batch.priceChanged': 'Price changed',
    'batch.usedIn': 'Used in processing {run}',
    'batch.producedBy': 'Produced by processing {run}',
    'batch.costFrom': 'Processing cost allocated from {run}',
    'batch.useChanged': 'Processing record for this batch changed',
    'batch.metalRecorded': 'Metal content recorded',
    'batch.metalsChanged': 'Metal content changed',
    'batch.metalRemoved': 'Metal content removed',
    'batch.assayRecorded': 'Assay recorded',
    'batch.assayApplied': 'Assay applied to this batch',
    'batch.assayWithdrawn': 'Assay result withdrawn',
    'batch.assayDeleted': 'Assay deleted',
    'batch.assayChanged': 'Assay changed',
    'batch.safetyAdded': 'Safety state recorded',
    'batch.safetyRemoved': 'Safety state removed',
    'batch.priceRequested': 'Receipt price request raised',
    'batch.priceRequestWithdrawn': 'Receipt price request withdrawn',
    'batch.priceRequestChanged': 'Receipt price request updated',
    'batch.prepayment': 'Prepayment applied',
    'batch.freight': 'Freight cost allocated',
    'batch.payment': 'Payment allocated',
    'batch.attachmentAdded': 'Attachment added',
    'batch.attachmentRemoved': 'Attachment removed',
    'batch.codIssued': 'Certificate of destruction issued',
    'batch.codPending': 'Certificate of destruction prepared — not issued yet',
    'batch.codVoided': 'Certificate of destruction voided',
    'batch.codChanged': 'Certificate of destruction updated',
    'batch.codPdf': 'Certificate of destruction PDF issued',
    'batch.sold': 'Sold',
    'batch.saleChanged': 'Sale changed',
    'batch.saleStock': 'Stock issued for the sale',
    'batch.saleAttributed': 'Sale attributed',
    'batch.invoiced': 'Invoiced',
    'batch.reserved': 'Reserved for a sales order',
    'batch.reservationReleased': 'Reservation released',
    'batch.reservationUsed': 'Reservation used by a shipment',
    'batch.shipped': 'Shipped',
    'batch.reportIssued': 'Traceability report issued',
    'batch.settlement': 'Sales settlement calculated',
    'batch.counted': 'Counted in stocktake {code}',
    // ── 分录 ─────────────────────────────────────────────────────────────────
    'journal.posted': 'Journal posted · {code}',
    'journal.reversal': 'Reversal journal posted · {code}',
    'journal.reversedBy': 'Journal {code} reversed by {by}',
    'journal.laterReversed': 'Later reversed by {by}',
    'journal.edited': 'Journal changed',
    // ── 审批(任何一种单据;{thing} 是单据类型与它的编号)───────────────────────
    'approval.submitted': '{Thing} submitted for approval',
    'approval.approved': '{Thing} approved',
    'approval.approvedLevel': '{Thing} approved (level {level})',
    'approval.rejected': '{Thing} rejected',
    'approval.auto': '{Thing} approved automatically (approvals were switched off)',
    'approval.other': '{Thing}: approval step recorded — {decision}',
    // ── 工单 ─────────────────────────────────────────────────────────────────
    'wo.created': 'Work order created',
    'wo.released': 'Work order released',
    'wo.closed': 'Work order closed',
    'wo.cancelled': 'Work order cancelled',
    'wo.amended': 'Work order amended',
    'wo.edited': 'Work order edited',
    'wo.lineAdded': 'Input line added',
    'wo.lineChanged': 'Input line changed',
    'wo.lineRemoved': 'Input line removed',
    'wo.expectedAdded': 'Expected output added',
    'wo.expectedChanged': 'Expected output changed',
    'wo.expectedRemoved': 'Expected output removed',
    // ── 盘点 ─────────────────────────────────────────────────────────────────
    'st.started': 'Stocktake started',
    'st.posted': 'Stocktake posted',
    'st.cancelled': 'Stocktake cancelled',
    'st.edited': 'Stocktake edited',
    'st.count': 'Count recorded',
    'st.recount': 'Count changed',
    'st.lineRemoved': 'Count removed',
    // ── 设备 ─────────────────────────────────────────────────────────────────
    'eq.cardCreated': 'Asset card created',
    'eq.cardEdited': 'Asset card edited',
    'eq.service': 'Service recorded',
    'eq.repair': 'Repair recorded',
    'eq.workChanged': 'Service record changed',
    'eq.workRemoved': 'Service record removed',
    'eq.capitalised': 'Work capitalised',
    'eq.down': 'Downtime started',
    'eq.up': 'Downtime ended',
    'eq.downChanged': 'Downtime changed',
    'eq.intervalSet': 'Service interval set',
    'eq.intervalChanged': 'Service interval changed',
    'eq.intervalRemoved': 'Service interval removed',
    'eq.handoverNote': 'Mentioned in a shift handover',
    // ── 交接班 ───────────────────────────────────────────────────────────────
    'ho.submitted': 'Shift handover submitted',
    'ho.acknowledged': 'Shift handover acknowledged',
    'ho.edited': 'Shift handover edited',
    'ho.item': 'Handover item added',
    'ho.downtime': 'Downtime noted in the handover',
    // ── 仓库申请 ─────────────────────────────────────────────────────────────
    'wr.raised': '{Kind} requested',
    'wr.approved': '{Kind} request approved and carried out',
    'wr.rejected': '{Kind} request rejected',
    'wr.withdrawn': '{Kind} request withdrawn',
    'wr.changed': '{Kind} request updated',
    'wr.kind.writeOff': 'write-off',
    'wr.kind.rollback': 'processing rollback',
    'wr.kind.codVoid': 'certificate void',
    'wr.kind.other': 'warehouse',
    // ══ AUDIT-TRAIL-1b-2 · 商务 ═════════════════════════════════════════════════
    // 一句事件史里的 detail 拆出单号之后剩下的那一段(照原样,它常夹着一个人写的理由)
    'label.details': 'Details',
    // ── 报价(§4:"Quote converted to sales order SO-…")──────────────────────
    'qt.created': 'Quote created',
    'qt.issued': 'Quote issued to the customer (version {version})',
    'qt.issuedPlain': 'Quote issued to the customer',
    'qt.declined': 'Quote declined',
    'qt.converted': 'Quote converted to sales order {code}',
    'qt.convertedPlain': 'Quote converted to a sales order',
    'qt.statusChanged': 'Quote status changed',
    'qt.edited': 'Quote details changed',
    'qt.deleted': 'Quote deleted',
    // ── 销售订单(它的事件史是主线:开票、发货、贷项凭证都记在订单上)──────────────
    'so.created': 'Sales order created',
    'so.createdFromQuote': 'Sales order created from quote {code}',
    'so.confirmed': 'Sales order confirmed',
    'so.closed': 'Sales order closed',
    'so.cancelled': 'Sales order cancelled',
    'so.deleted': 'Sales order deleted',
    'so.statusChanged': 'Sales order status changed',
    'so.edited': 'Sales order details changed',
    'so.issued': 'Sales order issued to the customer (version {version})',
    'so.issuedPlain': 'Sales order issued to the customer',
    'so.reserved': 'Stock reserved',
    'so.released': 'Reservation released',
    'so.invoiced': 'Invoiced',
    'so.invoiceVoided': 'Invoice voided',
    'so.shipped': 'Goods shipped',
    'so.creditNoted': 'Credit note raised',
    'so.amended': 'Sales order amended',
    'so.headerChanged': 'Notes and terms changed',
    'so.releaseRequested': 'Shipping release requested',
    'so.releaseApproved': 'Shipping release approved',
    'so.releaseRejected': 'Shipping release rejected',
    'so.releaseWithdrawn': 'Shipping release withdrawn',
    'so.releaseChanged': 'Shipping release updated',
    // ── 发货单 ───────────────────────────────────────────────────────────────
    'shp.created': 'Goods shipped',
    'shp.edited': 'Shipment details changed',
    'shp.lineAdded': 'Shipment line added',
    'shp.containerSet': 'Loaded into container',
    'shp.containerCleared': 'Taken out of container',
    'shp.issued': 'Delivery note issued (version {version})',
    // ── 联系人与附件(客户与供应商共用)────────────────────────────────────────
    'contact.added': 'Contact added',
    'contact.changed': 'Contact changed',
    'contact.removed': 'Contact removed',
    'att.changed': 'Attachment details changed',
    // ── 客户 ─────────────────────────────────────────────────────────────────
    'cus.created': 'Customer created',
    'cus.edited': 'Customer details changed',
    'cus.statusChanged': 'Customer status changed',
    'cus.deleted': 'Customer deleted',
    'cus.creditChanged': 'Credit settings changed',
    'cus.limitChanged': 'Credit limit changed',
    'cus.holdOn': 'Credit hold placed — shipments frozen',
    'cus.holdOff': 'Credit hold lifted',
    'cus.statementIssued': 'Statement of account issued',
    'cus.statementSuperseded': 'Statement of account superseded',
    'cus.statementPdf': 'Statement PDF issued (version {version})',
    'cus.chased': 'Payment chased',
    'cus.chaseSuperseded': 'Chase record corrected',
    'cus.promise': 'Payment promised',
    'cus.promiseOutcome': 'Promise outcome recorded',
    // ── 佣金协议 ─────────────────────────────────────────────────────────────
    'cm.created': 'Commission agreement created',
    'cm.edited': 'Commission agreement changed',
    'cm.deleted': 'Commission agreement deleted',
    // ── 供应商(§4:"Supplier submitted for review / approved / suspended / reinstated / archived")─────
    'sup.created': 'Supplier created',
    'sup.edited': 'Supplier details changed',
    'sup.deleted': 'Supplier deleted',
    'sup.submitted': 'Supplier submitted for review',
    'sup.approved': 'Supplier approved',
    'sup.rejected': 'Supplier rejected',
    'sup.activated': 'Supplier activated',
    'sup.suspended': 'Supplier suspended',
    'sup.reinstated': 'Supplier reinstated',
    'sup.blacklisted': 'Supplier blacklisted',
    'sup.archived': 'Supplier archived',
    'sup.restored': 'Supplier taken out of the archive',
    'sup.backToDraft': 'Supplier returned to draft',
    'sup.statusChanged': 'Supplier status changed',
    'sup.certAdded': 'Compliance certificate added',
    'sup.certChanged': 'Compliance certificate changed',
    'sup.certRemoved': 'Compliance certificate removed',
    // ── 货代(账上是一行供应商;M3)─────────────────────────────────────────────
    'fwd.created': 'Forwarder created',
    'fwd.edited': 'Forwarder details changed',
    'fwd.deleted': 'Forwarder deleted',
    'fwd.detailsSet': 'Logistics details recorded',
    'fwd.detailsChanged': 'Logistics details changed',
    'fwd.quoteAdded': 'Rate quote added',
    'fwd.quoteChanged': 'Rate quote changed',
    'fwd.quoteRemoved': 'Rate quote removed',
    // ── 集装箱 ───────────────────────────────────────────────────────────────
    'ctr.created': 'Container created',
    'ctr.edited': 'Container details changed',
    'ctr.deleted': 'Container deleted',
    'ctr.milestone': 'Milestone recorded',
    'ctr.detached': 'Shipment {code} taken out of this container',
    'ctr.docAdded': 'Document added to the checklist',
    'ctr.docReceived': 'Document received',
    'ctr.docNa': 'Document marked not applicable',
    'ctr.docPending': 'Document marked pending again',
    'ctr.docChanged': 'Document changed',
    'ctr.docRemoved': 'Document removed from the checklist',
    // ── 航段与港口 ───────────────────────────────────────────────────────────
    'lane.created': 'Lane created',
    'lane.edited': 'Lane changed',
    'lane.deleted': 'Lane removed',
    'lane.reviewed': 'Document checklist reviewed',
    'lane.reqAdded': 'Required document added',
    'lane.reqChanged': 'Required document changed',
    'lane.reqRemoved': 'Required document removed',
    'port.created': 'Port added',
    'port.edited': 'Port changed',
    'port.deleted': 'Port removed',
    // ── 公司执照 ─────────────────────────────────────────────────────────────
    'lic.created': 'Licence recorded',
    'lic.edited': 'Licence changed',
    'lic.statusChanged': 'Licence standing changed',
    'lic.deleted': 'Licence removed',
    // ── 只有清单页的记录(航段、港口、执照):一块合起来的审计记录 ───────────────────
    'listTrail.intro.lanes': 'Lanes, ports and their document checklists · newest first · Singapore time',
    'listTrail.intro.licences': 'Company licences · newest first · Singapore time',
    'listTrail.empty': 'Nothing has been recorded here yet.',
    // ══ AUDIT-TRAIL-1b-3 · 主数据与工具 ═══════════════════════════════════════
    // ── 删掉的主数据与单据(Q9 · Q21 · Q8):横幅;没有记人的只说日期 ─────────────────
    'banner.deleted': 'Deleted on {date} by {who}',
    'banner.deletedDate': 'Deleted on {date}',
    // ── 物料(页面上"必须化验的金属"那一块叫 Assay requirement)────────────────────
    'mat.created': 'Material created',
    'mat.edited': 'Material details changed',
    'mat.statusChanged': 'Material status changed',
    'mat.deleted': 'Material deleted',
    'mat.assayChanged': 'Assay requirement changed',
    'mat.assayFor': 'Assay required for',
    // ── 库位(页面上那一块叫 Allowed material classes)─────────────────────────────
    'loc.created': 'Storage location created',
    'loc.edited': 'Storage location details changed',
    'loc.deactivated': 'Storage location taken out of use',
    'loc.reactivated': 'Storage location back in use',
    'loc.classesChanged': 'Allowed material classes changed',
    'loc.classesLine': 'Allowed material classes',
    // ── 金属价格 ─────────────────────────────────────────────────────────────
    'mp.created': 'Metal price recorded',
    'mp.edited': 'Metal price changed',
    'mp.deleted': 'Metal price deleted',
    // ── 定价公式与它的条款申请(页面上:Send to the CFO)──────────────────────────
    'pf.created': 'Pricing formula created',
    'pf.edited': 'Pricing formula changed',
    'pf.deleted': 'Pricing formula deleted',
    'pf.restored': 'Pricing formula restored',
    'pf.deactivated': 'Pricing formula taken out of use',
    'pf.reactivated': 'Pricing formula back in use',
    'pf.metalSet': 'Payable % set',
    'pf.metalRemoved': 'Payable % removed',
    'pf.payableFor': 'Payable % · {metal}',
    'tr.sentNew': 'New pricing formula sent to the CFO',
    'tr.sentChange': 'Change to the pricing formula sent to the CFO',
    'tr.sentReactivate': 'Putting the pricing formula back in use sent to the CFO',
    'tr.sentOther': 'Terms sent to the CFO',
    'tr.approved': 'CFO approved the terms',
    'tr.rejected': 'CFO rejected the terms',
    'tr.withdrawn': 'Terms request withdrawn',
    'tr.changed': 'Terms request updated',
    // ── 任务(Q3:私人任务也是;说法与原来那段"变更记录"同一套词:step / ticked / taken off)──────────
    'task.created': 'Task created',
    'task.edited': 'Task edited',
    'task.deleted': 'Task deleted',
    'task.promoted': 'Made a team task',
    'task.ownerTransferred': 'Owner transferred',
    'task.stepLine': 'Step',
    'task.stepAdded': 'Step added',
    'task.stepRemoved': 'Step deleted',
    'task.stepRenamed': 'Step renamed',
    'task.stepRedated': 'Step re-dated',
    'task.stepDone': 'Step ticked',
    'task.stepUndone': 'Step un-ticked',
    'task.stepMoved': 'Step moved',
    'task.stepChanged': 'Step changed',
    'task.participantAdded': 'Participant added',
    'task.participantRemoved': 'Participant taken off',
    'task.participantLeft': 'Participant left',
    // ── 三个阈值面板(标题照面板自己的名字)────────────────────────────────────────
    'set.processing': 'Variance thresholds changed',
    'set.pricing': 'Price anomaly warning changed',
    'set.receiving': 'Discrepancy thresholds changed',
    // ══ AUDIT-TRAIL-1c-1 · 账上的单据(分录 · 发票 · 贷项通知 · 收付款 · 付款申请 · 费用 · 应付)═════════════
    // ── 结束了的单据(Q8):作废 / 冲销的横幅;链到镜像单的那一行 ─────────────────────────
    'banner.voided': 'Voided on {date} by {who}',
    'banner.voidedDate': 'Voided on {date}',
    'banner.reversedBy': 'Reversed by {code}',
    'banner.reversalOf': 'Reversal of {code}',
    // ── 分录(Q33:冲销是【一行】,链到冲销分录;它的行住在它自己的页上)──────────────────
    'je.posted': 'Journal posted',
    'je.reversalPosted': 'Reversal journal posted',
    'je.reversed': 'Journal reversed',
    'je.reversedOther': 'Journal {code} reversed',
    'je.reversedByLine': 'Reversed by',
    'je.reversesLine': 'Reverses',
    'je.debit': 'Debit {amount}',
    'je.credit': 'Credit {amount}',
    // ── 申请(人工分录 / 冲销 · 作废 / 贷项 · 六种付款申请)——"送去批" · 批准 · 驳回 · 撤回 ────────────
    'jr.sentEntry': 'Manual journal sent for approval',
    'jr.sentReversal': 'Reversal sent for approval',
    'jr.approvedEntry': 'Manual journal approved',
    'jr.approvedReversal': 'Reversal approved',
    'jr.rejectedEntry': 'Manual journal rejected',
    'jr.rejectedReversal': 'Reversal rejected',
    'jr.withdrawnEntry': 'Manual journal request withdrawn',
    'jr.withdrawnReversal': 'Reversal request withdrawn',
    'ir.sentVoid': 'Void sent for approval',
    'ir.sentCredit': 'Credit note sent for approval',
    'ir.approvedVoid': 'Void approved',
    'ir.approvedCredit': 'Credit note approved',
    'ir.rejectedVoid': 'Void request rejected',
    'ir.rejectedCredit': 'Credit note request rejected',
    'ir.withdrawnVoid': 'Void request withdrawn',
    'ir.withdrawnCredit': 'Credit note request withdrawn',
    'pr.sent.payment_out': 'Payment sent for approval',
    'pr.sent.payment_reversal': 'Payment reversal sent for approval',
    'pr.sent.bank_transfer': 'Bank transfer sent for approval',
    'pr.sent.bank_transfer_reversal': 'Bank transfer reversal sent for approval',
    'pr.sent.wht_remittance': 'WHT remittance sent for approval',
    'pr.sent.wht_remittance_reversal': 'WHT remittance reversal sent for approval',
    'pr.approved.payment_out': 'Payment approved',
    'pr.approved.payment_reversal': 'Payment reversal approved',
    'pr.approved.bank_transfer': 'Bank transfer approved',
    'pr.approved.bank_transfer_reversal': 'Bank transfer reversal approved',
    'pr.approved.wht_remittance': 'WHT remittance approved',
    'pr.approved.wht_remittance_reversal': 'WHT remittance reversal approved',
    'pr.rejected': 'Request rejected',
    'pr.withdrawn': 'Request withdrawn',
    'pr.done.payment_out': 'Paid',
    'pr.done.payment_reversal': 'Payment reversed',
    'pr.done.bank_transfer': 'Bank transfer made',
    'pr.done.bank_transfer_reversal': 'Bank transfer reversed',
    'pr.done.wht_remittance': 'WHT remitted',
    'pr.done.wht_remittance_reversal': 'WHT remittance reversed',
    'pr.changed': 'Request changed',
    'pr.docCcy': '{amount} (document currency)',
    // ── 发票 · 贷项通知 ─────────────────────────────────────────────────────────
    'inv.issued': 'Invoice issued',
    'inv.voided': 'Invoice voided',
    'inv.edited': 'Invoice changed',
    'inv.lineChanged': 'Invoice line changed',
    'inv.pdfIssued': 'Invoice PDF issued · version {version}',
    'cnote.issued': 'Credit note issued',
    'cnote.pdfIssued': 'Credit note PDF issued · version {version}',
    'cnote.changed': 'Credit note changed',
    // ── 收付款(Q31:冲销是新的一笔反向的单子 —— 它的建立读作"…reversed",不读作"…recorded")─────────────
    'pay.recordedOut': 'Payment recorded',
    'pay.recordedIn': 'Receipt recorded',
    'pay.reversedOut': 'Payment reversed',
    'pay.reversedIn': 'Receipt reversed',
    'pay.reversingLine': 'Reversing entry',
    'pay.changed': 'Payment changed',
    'pay.allocated': 'Allocated',
    'pay.allocatedTo': 'Payment allocated',
    'pay.allocationRemoved': 'Allocation removed',
    // ── 费用 · 报销单 · 资本化 · 定金冲抵 ──────────────────────────────────────────
    'exp.recorded': 'Expense recorded',
    'exp.reversed': 'Expense reversed',
    'exp.changed': 'Expense changed',
    'exp.claimSubmitted': 'Expense claim submitted',
    'exp.claimApproved': 'Expense claim approved',
    'exp.claimRejected': 'Expense claim rejected',
    'exp.claimWithdrawn': 'Expense claim withdrawn',
    'exp.claimChanged': 'Expense claim changed',
    'exp.capitalised': 'Capitalised into an asset',
    'exp.prepaymentReleased': 'Prepayment released against this bill',
    // ── 应付(Q5:只说钱的那一面)───────────────────────────────────────────────
    'pab.edited': 'Payable details changed',
    'pab.priceSet': 'Price set',
    // ══ AUDIT-TRAIL-1c-2 · 其余的单据与合同(销售 · 运费单 · 资产 · 对账单 · GST 期间 · 汇率 · 管理包 · 合同)═════════════
    //   前缀避开 messages/en.ts 里已经有的顶层键(gst. · pack. · bank. · assets. —— check-i18n 会把它们当成那边的键去找)
    // ── 撤回了的汇率(Q7):横幅;没有记人的只说日期 ───────────────────────────────────────
    'banner.withdrawn': 'Withdrawn on {date} by {who}',
    'banner.withdrawnDate': 'Withdrawn on {date}',
    // ── 销售(应收页,Q14)────────────────────────────────────────────────────────
    'sale.recorded': 'Sale recorded',
    'sale.attributed': 'Customer attributed to the sale',
    'sale.cogsPosted': 'Cost of sales posted',
    'sale.changed': 'Sale changed',
    // ── 运费单 ────────────────────────────────────────────────────────────────
    'frt.recorded': 'Freight document recorded',
    'frt.reversed': 'Freight document reversed',
    'frt.changed': 'Freight document changed',
    'frt.allocationChanged': 'Freight allocation changed',
    // ── 资产(财务那一页,Q10)────────────────────────────────────────────────────
    'fa.inService': 'Put into service',
    'fa.disposed': 'Asset disposed',
    'fa.costAdded': 'Cost added',
    'fa.costChanged': 'Cost entry changed',
    'fa.depreciated': 'Depreciation posted',
    'fa.rebased': 'Depreciation re-based',
    'fa.disposalSent': 'Disposal sent for approval',
    'fa.disposalApproved': 'Disposal approved',
    'fa.disposalRejected': 'Disposal rejected',
    'fa.disposalWithdrawn': 'Disposal request withdrawn',
    'fa.disposalChanged': 'Disposal request changed',
    // ── 对账单(Q6 · Q24)───────────────────────────────────────────────────────
    'bst.imported': 'Bank statement imported',
    'bst.lines': 'Lines',
    'bst.deleted': 'Bank statement deleted',
    'bst.reconciled': 'Bank statement reconciled',
    'bst.unreconciled': 'Reconciliation undone',
    'bst.changed': 'Bank statement changed',
    'bst.lineMatched': 'Statement line matched',
    'bst.lineUnmatched': 'Statement line unmatched',
    'bst.lineIgnored': 'Statement line ignored',
    'bst.lineUnignored': 'Statement line no longer ignored',
    'bst.lineChanged': 'Statement line changed',
    'bst.reconChanged': 'Reconciliation record changed',
    // ── GST 期间(Q22 · Q23:更正件说它为哪一期开的;申报那一刻抄下来的每一格并进申报那一条,只说英文)──────────
    'gstp.opened': 'GST period opened',
    'gstp.correctionOpened': 'Correction opened for {code}',
    'gstp.correctionOpenedPlain': 'Correction period opened',
    'gstp.sent': 'GST return sent for approval',
    'gstp.approved': 'GST return approved',
    'gstp.rejected': 'GST return rejected',
    'gstp.withdrawn': 'GST return request withdrawn',
    'gstp.requestChanged': 'GST return request changed',
    'gstp.locked': 'GST return locked · {n} boxes',
    'gstp.box': 'Box {n}',
    'gstp.filed': 'GST return filed',
    'gstp.changed': 'GST period changed',
    // ── 汇率(一件事两行:录入 · 更正 · 撤回由修改史那一行说出是哪一种)──────────────────────────
    'fxr.recorded': 'Exchange rate recorded',
    'fxr.corrected': 'Exchange rate corrected',
    'fxr.withdrawn': 'Exchange rate withdrawn',
    'fxr.changed': 'Exchange rate changed',
    // ── 管理包(Q25)──────────────────────────────────────────────────────────
    'mpk.produced': 'Management pack produced',
    'mpk.superseded': 'Management pack replaced',
    'mpk.replacedBy': 'Replaced by',
    'mpk.changed': 'Management pack changed',
    // ── 合同(Q21:没有 pricing.view 的读者,CFO 的决定那几行是 Restricted —— 读规则说的,不在这里)──────────────
    'con.created': 'Contract created',
    'con.edited': 'Contract changed',
    'con.activated': 'Contract activated',
    'con.suspended': 'Contract suspended',
    'con.statusChanged': 'Contract status changed',
    'con.deleted': 'Contract deleted',
    'con.termAdded': '{Thing} added',
    'con.termChanged': '{Thing} changed',
    'con.termRemoved': '{Thing} removed',
    'con.linked': 'Linked to {code}',
    'con.linkedPlain': 'Linked to an order',
    'tr.sentActivate': 'Contract activation sent to the CFO',
    // ══ AUDIT-TRAIL-1c-3 · 期末、设置与清单页上的记录 ═════════════════════════════════════════════════
    // 前缀避开 messages/en.ts 的顶层命名空间(check-i18n 会把那些前缀的字面量当成界面键):plock · gstset · coprof · yclose ·
    //   fcst · fcl · bip。
    // ── 锁期面板(Q25 · Q29 · M7):§4 的 "Month closed up to …" / "Month reopened from …" / "Period lock moved";
    //    挪了多少由下面一行说,标签与页面上那一格同一句("Period locked before")──────────────────────────────
    'plock.moved': 'Period lock moved',
    'plock.set': 'Period lock set',
    'plock.removed': 'Period lock removed',
    'plock.monthClosed': 'Month closed up to {date}',
    'plock.monthReopened': 'Month reopened from {date}',
    'plock.closeChanged': 'Month close changed',
    // ── GST 设置面板(Q25):注册开关与注册号 ─────────────────────────────────────────────────────
    'gstset.registered': 'GST registration switched on',
    'gstset.deregistered': 'GST registration switched off',
    'gstset.changed': 'GST settings changed',
    // ── 公司资料 ────────────────────────────────────────────────────────────────────────
    'coprof.created': 'Company profile created',
    'coprof.changed': 'Company profile changed',
    // ── 年结(/finance/close 年结那一块)──────────────────────────────────────────────────────
    'yclose.closed': 'Year closed up to {date}',
    'yclose.reopened': 'Year reopened · year ending {date}',
    'yclose.changed': 'Year close changed',
    // ── 分录:一张按来源说得出是什么的分录(只在分录自己的页与清单块上 —— 重估 / 折旧 / 工资 / 年结的批次)──────
    'je.posted.revaluation': 'FX revaluation posted',
    'je.posted.depreciation': 'Depreciation posted',
    'je.posted.payroll': 'Payroll journal posted',
    'je.posted.year_close': 'Year-end closing journal posted',
    // ── 批量汇率(Q16):一次批量录入是一条 ───────────────────────────────────────────────────
    'fxr.recordedMany': 'Exchange rates recorded · {n} rates',
    // ── 现金预测(Q16:冻结一张新的、作废旧的一张是一次操作)与常设行 ─────────────────────────────────
    'fcst.frozen': 'Cash forecast frozen',
    'fcst.superseded': 'Cash forecast replaced',
    'fcst.replacedBy': 'Replaced by',
    'fcst.changed': 'Cash forecast changed',
    'fcl.added': 'Recurring line added',
    'fcl.changed': 'Recurring line changed',
    'fcl.switchedOff': 'Recurring line switched off',
    'fcl.switchedOn': 'Recurring line switched back on',
    'fcl.removed': 'Recurring line removed',
    // ── 行内转账自己的一次改动(此前借了付款申请的 "Request changed")──────────────────────────────────────
    'btr.changed': 'Bank transfer changed',
    // ── 银行导入模板(页面上叫 mapping)────────────────────────────────────────────────────────
    'bip.created': 'Import mapping saved',
    'bip.changed': 'Import mapping changed',
    'bip.deleted': 'Import mapping deleted',
    // ── 清单块的开场白(每一页一句;字面量写全 —— check-trail-wording 按字面认"这个键有人用")─────────────
    'listTrail.intro.yearCloses': 'Year closes · newest first · Singapore time',
    'listTrail.intro.revaluations': 'FX revaluation runs · newest first · Singapore time',
    'listTrail.intro.depreciation': 'Depreciation runs · newest first · Singapore time',
    'listTrail.intro.fxRates': 'Exchange rates on this page, and withdrawn rates · newest first · Singapore time',
    'listTrail.intro.forecasts': 'Frozen forecasts and recurring lines · newest first · Singapore time',
    'listTrail.intro.payroll': 'Payroll journals · newest first · Singapore time',
    'listTrail.intro.costSettlement': 'Processing-cost remittance journals and relief expenses · newest first · Singapore time',
    'listTrail.intro.wht': 'WHT remittances · newest first · Singapore time',
    'listTrail.intro.transfers': 'Bank transfers · newest first · Singapore time',
    'listTrail.intro.importMappings': 'Import mappings, including deleted ones · newest first · Singapore time',
    'listTrail.intro.deletedStatements': 'Deleted bank statements · newest first · Singapore time',
    // ── 一张卡片 / 一行里的那一块(人工分录申请 · 报销单):折起来,点开才看 ─────────────────────────────
    'rowTrail.summary': 'Audit trail',
    // ════ AUDIT-TRAIL-1d-1(Tim 2026-10-04)────────────────────────────────────────
    // ── 账号与授权(I03 · I04 · I12 · G59 · G60;Q9 · Q22)—— 账号页从账号这一边说,角色页从角色这一边说 ─────
    'acct.roleGranted': 'Role granted: {role}',
    'acct.roleRemoved': 'Role removed: {role}',
    'acct.grantedTo': 'Role granted to {who}',
    'acct.removedFrom': 'Role removed from {who}',
    'acct.extraLinked': 'Additional login linked',
    'acct.extraUnlinked': 'Additional login unlinked',
    'acct.primaryLinked': 'Login linked to employee {code}',
    'acct.primaryUnlinked': 'Login unlinked from employee {code}',
    'acct.primaryLinkedAny': 'Login linked to an employee',
    'acct.primaryUnlinkedAny': 'Login unlinked from an employee',
    // ── 审批方针(F45–F48;Q25)────────────────────────────────────────────────────
    'pol.switchedOn': 'Approvals switched on',
    'pol.switchedOff': 'Approvals switched off',
    'pol.changed': 'Approval policy changed',
    // ── 员工 · 任职履历 · 调薪申请(G32–G44 · G61;Q10 · Q30)────────────────────────────
    'emp.added': 'Employee added',
    'emp.edited': 'Employee details changed',
    'emp.deleted': 'Employee deleted',
    'emp.anonymised': 'Personal data anonymised',
    'emp.loginLinked': 'Login account linked',
    'emp.loginUnlinked': 'Login account unlinked',
    'emp.hired': 'Hired',
    'emp.confirmed': 'Confirmed after probation',
    'emp.promotion': 'Promoted',
    'emp.transfer': 'Transferred',
    'emp.typeChange': 'Employment type changed',
    'emp.statusChange': 'Employment status changed',
    'emp.separated': 'Left the company',
    'emp.categoryChange': 'Work category changed',
    'emp.salarySet': 'Salary set',
    'emp.salaryChanged': 'Salary changed',
    'emp.historyRecorded': 'Employment change recorded',
    'emp.historyChanged': 'Employment record corrected',
    'emp.noteReview': 'Confirmed through a performance review',
    'emp.noteSalaryRequest': 'Salary change request',
    'scr.requested': 'Salary change requested',
    'scr.approved': 'Salary change approved',
    'scr.rejected': 'Salary change rejected',
    'scr.withdrawn': 'Salary change request withdrawn',
    'scr.changed': 'Salary change request changed',
    // ── 培训记录 · 部门 ──────────────────────────────────────────────────────────────────
    'trn.added': 'Training recorded',
    'trn.changed': 'Training record changed',
    'trn.deleted': 'Training record deleted',
    'dept.created': 'Department created',
    'dept.changed': 'Department changed',
    'dept.deactivated': 'Department deactivated',
    'dept.reactivated': 'Department reactivated',
    'dept.deleted': 'Department deleted',
    // ── 字典(六本;M11)· 导入批次(F97)—— 前缀是 dictv.,不是 dict.:后者是 messages/en.ts 的一个顶层命名空间(字典页),
    //    check-i18n 会把 'dictv.added' 当成一个界面键去两边找(1c-3 选前缀时记过的同一条)──────────────────────────
    'dictv.added': '{Thing} added',
    'dictv.changed': '{Thing} changed',
    'dictv.deactivated': '{Thing} deactivated',
    'dictv.reactivated': '{Thing} reactivated',
    'imp.imported.one': '1 {thing} imported from a file',
    'imp.imported.many': '{n} {thing} records imported from a file',
    'listTrail.intro.importBatches': 'Bulk imports · newest first · Singapore time',
    // ── 结束了的记录(Q25 · Q26):删掉的角色 · 员工 · 部门 · 培训记录 —— 用 banner.deleted / banner.deletedDate ──
    // ════ AUDIT-TRAIL-1d-2(Tim 2026-10-04)── 请假与考勤 ────────────────────────────────────────────
    //    前缀是 lv. / lgr. / mc. / ot. / attp.(att. 已经是附件的),不是 leave. / claims. / overtime. / attendance.:后四个是 messages/en.ts 的顶层命名空间
    //    (那几页),check-i18n 会把这里的键当成界面键去两边找(dictv. 的同一条)
    // ── 请假(G01–G04;Q12:取消改写决定那一对戳,按状态说)──────────────────────────────────────
    'lv.days.one': '1 day',
    'lv.days.many': '{n} days',
    'lv.requested': 'Leave requested: {days} of {type}',
    'lv.approved': 'Leave approved',
    'lv.rejected': 'Leave rejected',
    'lv.cancelled': 'Leave cancelled',
    'lv.changed': 'Leave request changed',
    'lv.daysTaken': 'Days taken from the balance',
    'lv.daysReturned': 'Days returned to the balance',
    'lv.exception': 'Days entered by hand (exception)',
    // ── 假期发放(G06;一次结转是一条 —— 清单块按操作并)───────────────────────────────────────────────
    'lgr.carried': 'Unused leave carried forward: {days}',
    'lgr.carriedMany': 'Unused leave carried forward · {n} people',
    'lgr.granted': 'Leave granted: {days}',
    'lgr.changed': 'Leave grant changed',
    'lgr.removed': 'Leave grant removed',
    // ── 医疗报销(G07–G11)────────────────────────────────────────────────────────────────────
    'mc.submitted': 'Medical claim submitted: {amount}',
    'mc.approved': 'Medical claim approved',
    'mc.rejected': 'Medical claim rejected',
    'mc.withdrawn': 'Medical claim withdrawn',
    'mc.expenseRaised': 'Expense raised to pay the claim',
    'mc.changed': 'Medical claim changed',
    // ── 加班(G16–G22;Q35:驳回照页面的话说 "Sent back")──────────────────────────────────────────
    'ot.started': 'Overtime batch started',
    'ot.submitted': 'Overtime sent for approval',
    'ot.submittedHours': 'Overtime sent for approval: {hours} hours',
    'ot.withdrawn': 'Overtime taken back for changes',
    'ot.approved': 'Overtime approved',
    'ot.sentBack': 'Overtime sent back',
    'ot.reversed': 'Overtime reversed',
    'ot.discarded': 'Overtime batch discarded',
    'ot.changed': 'Overtime batch changed',
    'ot.lineAdded': 'Overtime line added',
    'ot.lineRemoved': 'Overtime line removed',
    'ot.lineChanged': 'Overtime line changed',
    // ── 考勤(G56–G58;Q12:记录开始之前只剩最近那一次完成与重开 —— 照直说)──────────────────────────
    'attp.opened': 'Attendance period opened',
    'attp.completed': 'Attendance period completed',
    'attp.reopened': 'Attendance period reopened',
    'attp.frozen': 'Attendance figures frozen',
    'attp.joinersAdded': 'New joiners added to the sheet',
    'attp.recorded': 'Attendance recorded',
    'attp.changed': 'Attendance period changed',
    'attp.people': 'People',
    'attp.latestOnly': 'Only the latest completion and reopening of this month were kept before the log began.',
    'listTrail.intro.leaveGrants': 'Leave grants for this leave year · newest first · Singapore time',
} as const

export type TrailTextKey = keyof typeof TRAIL_TEXT
export type TrailText = typeof TRAIL_TEXT
