-- db/tables/approval_log.sql
-- APR-1:审批留痕表 —— 只记录,不把关,不改变任何行为
--
-- 【为什么它排第一】所有后续切次都需要它,而它不依赖任何东西。Doc 1 要的"谁批的、
-- 谁驳的、谁会签的、什么时候"在今天【没有任何一张表能回答】:三条 HR 链把决定写成
-- 行上的列并【覆盖】它们,所以"驳回 → 重提 → 批准"之后,驳回那一次不留痕迹。
-- 这不是在现有链上补一层报表,而是一张不存在的表。
--
-- 五个决定已定,记在 docs/approvals-scoping.md,后续切次读它不再重问:
--   一级按【角色】路由;二级路由到一个【具名的人】(配置成 user_id,不新建 cfo 角色);
--   阈值放 finance_settings、按【本位币】比、用【单据自己存的汇率】(金额待定);
--   修改把金额抬过阈值 → 原审批作废并重新路由;HR 三条链保留各自的引擎,但【写这张表】。
--
-- ════════════════════════════════════════════════════════════════════════════
-- 【只增不改】pricing_formula_history / employment_history 的形状。守卫【自己报名】,
-- 不靠外键顺带挡住 —— FIN-31 的教训:processing_cost_entries 的硬删此前只是被一条
-- 审计表外键"顺便"拦着,那不是拒绝,只是巧合,而且没有名字。
--
-- 【主体是 (subject_type, subject_id),不是可空外键 XOR】—— 取舍写在
-- docs/approvals-scoping.md,摘要:payment_allocations 的 num_nonnulls XOR 在【四路】
-- 上成立,这里至少六路、将来八路以上,八列里七列恒为 NULL 是一张跟每个新动作打架的表。
-- 外键在【这里】的保护力也弱:主体一律软删(原则 7),本表只增,所以它指的行不会消失。
-- 真实的失误是 subject_type 打错字,而那正好由 CHECK 枚举挡住。
-- 【失去了什么,明写】没有东西阻止 subject_id 指向一行不存在的记录。补偿是
-- 【只有一个写入口】record_approval_decision(),它先核对主体存在再插入,不存在就点名拒绝。
--
-- 【金额冻结在决定当时】单据此后会变(采购单的 estimated_total_ccy 一改明细就动),
-- 而留痕必须能回答"批的时候它值多少",不能回头 join 一个已经变了的数 ——
-- 与 FIN-27 把条款抄到承诺记录上是同一条理由。也正是决定 4(改价抬过阈值就作废重路由)
-- 得以判断的依据:拿新金额跟【冻结的那个】比。
--
-- NOTE: introduced by db/migrations/2026-08-09-apr1-approval-log.sql.
-- First-run script (plain CREATEs).

CREATE TABLE public.approval_log (
    id                  uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    -- 【留痕需要一个全序,时间戳给不了】decided_at 用 now() = 事务时间,同一个事务里
    -- 的两次决定拿到【同一个】时间戳,于是"先驳回后批准"与"先批准后驳回"在排序上
    -- 分不开 —— 而那正是本表要讲清楚的那件事。seq 是插入顺序的裁决者。
    -- (batch_assay_status 用 code 破同一个平局,理由一样:一个事务里 created_at 相同。)
    seq                 bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY UNIQUE,

    -- ── 主体 ────────────────────────────────────────────────────────────────
    -- 枚举【就是】将来加动作时唯一要改的地方(界面文案的后缀集合也从这里现读,
    -- 与 operations_now.item_type 喂 check-i18n 是同一个做法)。
    subject_type        text NOT NULL CHECK (subject_type IN (
                            'leave_request', 'medical_claim', 'performance_review',
                            'purchase_order', 'payment', 'expense',
                            'pricing_formula', 'stocktake',
                            -- WO-1b:工单。可审批的动作是【放行】—— 不是新建
                            -- (草稿谁都可以写),也不是收工(那是事后记录)。
                            'work_order')),
    subject_id          uuid NOT NULL,
    -- 人读的编号,冻结在当时 —— 单据可以改名/作废,留痕不跟着变
    subject_code        text,

    -- ── 决定 ────────────────────────────────────────────────────────────────
    -- countersigned:Doc 1 点名的"会签",【预留取值,本切没有路径写它】——
    -- 与 purchase_orders.approval_status 同一个性质:先把词定下来,免得下一切另起一个。
    -- auto_approved:不是有人做的决定,而是【系统在没有审批流时盖的章】。
    -- 三张既有采购单就是这样来的,回填时用的正是这个值(见文件尾)。
    decision            text NOT NULL CHECK (decision IN (
                            'submitted', 'approved', 'rejected',
                            'acknowledged', 'countersigned', 'auto_approved',
                            -- APR-2:金额被改到越过阈值 → 原审批作废(决定 4)。
                            -- 不是谁做的决定,是系统事件 —— 但必须看得见,否则
                            -- "批过又没批"在日志里读不出来(同 auto_approved 的性质)。
                            'approval_voided')),
    -- 1 = 主管,2 = 阈值以上的具名审批人。HR 三条链现在没有层级 → NULL。
    level               smallint CHECK (level IS NULL OR level IN (1, 2)),
    -- 决定人。auth.uid();回填行为 NULL(见 is_reconstructed)。
    actor_user_id       uuid,
    decided_at          timestamptz NOT NULL DEFAULT now(),
    note                text,

    -- ── 金额:冻结在决定当时,全有或全无 ────────────────────────────────────
    -- 【没有金额的主体一律留空,不硬塞】请假的"额度"是【天数】,不是钱,不塞进
    -- 币种列;绩效评估根本没有金额。
    amount_ccy          numeric,
    currency            text REFERENCES public.currencies (code),
    fx_rate             numeric CHECK (fx_rate IS NULL OR fx_rate > 0),
    amount_base         numeric,

    -- ── 回填标记 ────────────────────────────────────────────────────────────
    -- 【重建的事实与当场记下的事实必须分得开】。decided_at/decided_by 是真的记录,
    -- 据它重建终态是【读记录】不是【编事实】;但"完整"是假的 —— 被覆盖掉的驳回
    -- 已经没有了。所以重建行自己说自己是重建的。
    is_reconstructed    boolean NOT NULL DEFAULT false,
    reconstruction_note text,

    created_at          timestamptz NOT NULL DEFAULT now(),

    CONSTRAINT approval_log_amount_shape CHECK (
        (amount_ccy IS NULL AND currency IS NULL AND fx_rate IS NULL AND amount_base IS NULL)
        OR
        (amount_ccy IS NOT NULL AND currency IS NOT NULL AND fx_rate IS NOT NULL AND amount_base IS NOT NULL)
    ),
    CONSTRAINT approval_log_reconstruction_shape CHECK (
        NOT is_reconstructed OR reconstruction_note IS NOT NULL
    )
);

CREATE INDEX idx_approval_log_subject
    ON public.approval_log (subject_type, subject_id, seq);
CREATE INDEX idx_approval_log_actor
    ON public.approval_log (actor_user_id, decided_at DESC);

COMMENT ON TABLE public.approval_log IS
    '审批留痕,只增不改(APR-1)。谁、对什么、做了什么决定、什么时候、当时值多少。三条 HR 链保留各自的引擎但写这里;采购单等动作在 APR-2 起接入。主体是 (subject_type, subject_id) 而非可空外键 XOR —— 取舍与代价见 docs/approvals-scoping.md。';

-- ════════════════════════════════════════════════════════════════════════════
-- 只增不改的守卫。【自己报名】—— 不靠外键顺带挡(FIN-31)。
-- ════════════════════════════════════════════════════════════════════════════
-- 守卫函数体在 db/functions/guard_approval_log_append_only.sql

CREATE TRIGGER trg_approval_log_append_only
    BEFORE UPDATE OR DELETE ON public.approval_log
    FOR EACH ROW EXECUTE FUNCTION public.guard_approval_log_append_only();

ALTER TABLE public.approval_log ENABLE ROW LEVEL SECURITY;

-- 读:谁看得见留痕。审批史横跨模块,而【读它的人是要审计的人】——
-- 与 auditor 持有全部 module.*.view 是同一条思路:先给读得到相关模块的人。
-- 写:【没有 INSERT 策略】。唯一的写入口是 record_approval_decision()(属主权限),
-- 应用侧任何直接 INSERT 都会被 RLS 挡下 —— 留痕不该有第二个写法。
CREATE POLICY "approval_log select by permission"
    ON public.approval_log
    AS PERMISSIVE FOR SELECT TO authenticated
    USING (
        CASE subject_type
            WHEN 'leave_request'      THEN has_permission('module.hr.view'::text)
            WHEN 'medical_claim'      THEN has_permission('module.hr.view'::text)
            WHEN 'performance_review' THEN has_permission('module.hr.view'::text)
            WHEN 'purchase_order'     THEN has_permission('module.purchasing.view'::text)
            WHEN 'payment'            THEN has_permission('module.finance.view'::text)
            WHEN 'expense'            THEN has_permission('module.finance.view'::text)
            WHEN 'pricing_formula'    THEN has_permission('module.pricing.view'::text)
            WHEN 'stocktake'          THEN has_permission('module.stocktakes.view'::text)
            ELSE false
        END
    );

REVOKE SELECT ON public.approval_log FROM authenticated, anon;
GRANT SELECT (id, seq, subject_type, subject_id, subject_code, decision, level,
              actor_user_id, decided_at, note, amount_ccy, currency, fx_rate,
              amount_base, is_reconstructed, reconstruction_note, created_at)
    ON public.approval_log TO authenticated;
