-- db/tables/approval_log.sql
-- APR-1:审批留痕表 —— 只记录,不把关,不改变任何行为
--
-- 【为什么它排第一】所有后续切次都需要它,而它不依赖任何东西。Doc 1 要的"谁批的、
-- 谁驳的、谁会签的、什么时候"在今天【没有任何一张表能回答】:三条 HR 链把决定写成
-- 行上的列并【覆盖】它们,所以"驳回 → 重提 → 批准"之后,驳回那一次不留痕迹。
-- 这不是在现有链上补一层报表,而是一张不存在的表。
--
-- 五个决定已定,记在 docs/approvals-scoping.md,后续切次读它不再重问:
--   一级按【角色】路由;二级路由到一个【具名的人】(配置成 user_id,不新建 cfo 角色);
--   阈值放 finance_settings、按【本位币】比、用【单据自己存的汇率】(金额待定);
--   修改把金额抬过阈值 → 原审批作废并重新路由;HR 三条链保留各自的引擎,但【写这张表】。
--
-- ════════════════════════════════════════════════════════════════════════════
-- 【只增不改】pricing_formula_history / employment_history 的形状。守卫【自己报名】,
-- 不靠外键顺带挡住 —— FIN-31 的教训:processing_cost_entries 的硬删此前只是被一条
-- 审计表外键"顺便"拦着,那不是拒绝,只是巧合,而且没有名字。
--
-- 【主体是 (subject_type, subject_id),不是可空外键 XOR】—— 取舍写在
-- docs/approvals-scoping.md,摘要:payment_allocations 的 num_nonnulls XOR 在【四路】
-- 上成立,这里至少六路、将来八路以上,八列里七列恒为 NULL 是一张跟每个新动作打架的表。
-- 外键在【这里】的保护力也弱:主体一律软删(原则 7),本表只增,所以它指的行不会消失。
-- 真实的失误是 subject_type 打错字,而那正好由 CHECK 枚举挡住。
-- 【失去了什么,明写】没有东西阻止 subject_id 指向一行不存在的记录。补偿是
-- 【只有一个写入口】record_approval_decision(),它先核对主体存在再插入,不存在就点名拒绝。
--
-- 【金额冻结在决定当时】单据此后会变(采购单的 estimated_total_ccy 一改明细就动),
-- 而留痕必须能回答"批的时候它值多少",不能回头 join 一个已经变了的数 ——
-- 与 FIN-27 把条款抄到承诺记录上是同一条理由。也正是决定 4(改价抬过阈值就作废重路由)
-- 得以判断的依据:拿新金额跟【冻结的那个】比。
--
-- NOTE: introduced by db/migrations/2026-08-09-apr1-approval-log.sql.
-- First-run script (plain CREATEs).

CREATE TABLE public.approval_log (
    id                  uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    -- 【留痕需要一个全序,时间戳给不了】decided_at 用 now() = 事务时间,同一个事务里
    -- 的两次决定拿到【同一个】时间戳,于是"先驳回后批准"与"先批准后驳回"在排序上
    -- 分不开 —— 而那正是本表要讲清楚的那件事。seq 是插入顺序的裁决者。
    -- (batch_assay_status 用 code 破同一个平局,理由一样:一个事务里 created_at 相同。)
    seq                 bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY UNIQUE,

    -- ── 主体 ────────────────────────────────────────────────────────────────
    -- 枚举【就是】将来加动作时唯一要改的地方(界面文案的后缀集合也从这里现读,
    -- 与 operations_now.item_type 喂 check-i18n 是同一个做法)。
    subject_type        text NOT NULL CHECK (subject_type IN (
                            'leave_request', 'medical_claim', 'performance_review',
                            'purchase_order', 'payment', 'expense',
                            'pricing_formula', 'stocktake',
                            -- ★ APR-3:报销单。它是【唯一一个形状就是审批、却漏在
                            -- 这份枚举外】的单据(APR-0 §3.1 量出来的),而它自己的
                            -- status 就是审批态(submitted/withdrawn/approved/rejected)。
                            -- 加一个取值要动四处,而其中只有【读策略那一支】漏掉了
                            -- 不会有任何东西变红 —— 见本文件末尾那条策略里的同名分支。
                            'expense_claim',
                            -- WO-1b:工单。可审批的动作是【放行】—— 不是新建
                            -- (草稿谁都可以写),也不是收工(那是事后记录)。
                            'work_order',
                            -- PAY-REQ-1:付款申请(出款与冲销付款)—— CFO 批每一张。
                            -- 'payment' 那一格是 APR-1 预留的,从来没有路径写它;
                            -- 被批的是【申请】,不是付款行(付款行生下来就已经过账)。
                            'payment_request',
                            -- ROLE-1 Batch 2a(Q3 / Q9):供应商的送审、批准、驳回 —— CFO 批。
                            -- 【不是审批引擎的一条链】:没有金额、没有档位,审批开关不关它。
                            'supplier',
                            -- PAYROLL-APR-1:工资过账与撤销的申请 —— CFO 批每一张。
                            -- 被批的是【申请】(payroll_requests),不是工资期本身。
                            'payroll_request',
                            -- ROLE-1 Batch 4b:收货定价申请 —— CFO 批每一张,批准当场过账。
                            -- 被批的是【申请】(receipt_price_requests),不是收货本身。
                            'receipt_price_request',
                            -- APR-5a:贷项通知与作废发票的申请 —— CFO 批每一张,批准当场过账。
                            -- 被批的是【申请】(invoice_requests),不是发票或贷项本身。
                            'invoice_request')),
    subject_id          uuid NOT NULL,
    -- 人读的编号,冻结在当时 —— 单据可以改名/作废,留痕不跟着变
    subject_code        text,

    -- ── 决定 ────────────────────────────────────────────────────────────────
    -- countersigned:Doc 1 点名的"会签",【预留取值,本切没有路径写它】——
    -- 与 purchase_orders.approval_status 同一个性质:先把词定下来,免得下一切另起一个。
    -- auto_approved:不是有人做的决定,而是【单据生下来就是 approved】——
    -- 没有任何人按过任何东西。三张既有采购单就是这样来的
    -- (create_purchase_order 在审批关着时让单据直接生成 confirmed/approved),
    -- 回填时用的正是这个值(见文件尾)。
    -- ★★ APR-3(Tim 的 Q7)把这句定义【收窄】了,而收窄之前它是错的:
    --   工单放行此前在审批关着时也写 auto_approved,note 里逐字写着
    --   「没有人做过这个决定」—— 而放行是一个人按下去的动作,旁边就记着是谁。
    --   从 APR-3 起 release_work_order 两条分支都写 approved(与 HR 三条链、
    --   与盘点过账同一条裁定:开着还是关着,决定都是人做的)。
    -- ════════════════════════════════════════════════════════════════════════
    -- ★★【HR 那三条链【永远】不写 auto_approved —— 而这是一条裁定,不是巧合】
    -- ════════════════════════════════════════════════════════════════════════
    -- (Tim 的 Q3,APR-2 落地;APR-3 把同一条推广到工单与盘点。)
    -- 【理由,一句话】请假 · 医疗申报 · 绩效评估【自带引擎】:它们的决定路径
    -- (decide_leave_request / decide_medical_claim / approve_review)从来不读
    -- approvals_enabled() —— 一个人打开那张单、看过、按了准或不准,
    -- **审批开关开着还是关着,这件事都发生了,而且是同一个人做的**。
    -- ☞ 于是写 auto_approved 会是一句【关于内控的假话】:它声称"没有人做过
    --   这个决定",而同一行的 actor_user_id 里就记着是谁。
    -- 【对照:采购单为什么可以写】create_purchase_order 在审批关着时让单据
    --   **生下来就是 approved** —— 那条路上确实没有任何人按过任何东西。
    --   ★ 区别不在"开关开没开",在【有没有一个人做过这个动作】。
    -- 【它的代价,照直说】approvals_enabled 为 false 时,HR 那三条链的留痕
    --   与 true 时【长得一模一样】(都是 approved / level 为 NULL)——
    --   也就是说这张表回答不了"这个决定是在审批生效期间做的吗"。
    --   那个问题要靠 finance_settings_history 的时间线去交叉,而那是对的:
    --   **一行留痕该说的是那一刻真的发生了什么,不是当时的配置是什么。**
    -- ⚠★【线上那一行历史数据【没有】被改写,这是刻意的】2026-08-16 有一行
    --   work_order / auto_approved。本表只增不改,而改写它等于伪造一条
    --   当时真实记下来的记录。☞ 所以这张表会同时存在两种写法,而它们的
    --   分界是一个【日期】不是一条规则:APR-3 之前的工单留痕按旧定义读。
    decision            text NOT NULL CHECK (decision IN (
                            'submitted', 'approved', 'rejected',
                            'acknowledged', 'countersigned', 'auto_approved',
                            -- APR-2:金额被改到越过阈值 → 原审批作废(决定 4)。
                            -- 不是谁做的决定,是系统事件 —— 但必须看得见,否则
                            -- "批过又没批"在日志里读不出来(同 auto_approved 的性质)。
                            'approval_voided')),
    -- 1 = 主管,2 = 阈值以上的具名审批人。HR 三条链现在没有层级 → NULL。
    level               smallint CHECK (level IS NULL OR level IN (1, 2)),
    -- 决定人。auth.uid();回填行为 NULL(见 is_reconstructed)。
    actor_user_id       uuid,
    decided_at          timestamptz NOT NULL DEFAULT now(),
    note                text,

    -- ── 金额:冻结在决定当时,全有或全无 ────────────────────────────────────
    -- 【没有金额的主体一律留空,不硬塞】请假的"额度"是【天数】,不是钱,不塞进
    -- 币种列;绩效评估根本没有金额。
    amount_ccy          numeric,
    currency            text REFERENCES public.currencies (code),
    fx_rate             numeric CHECK (fx_rate IS NULL OR fx_rate > 0),
    amount_base         numeric,

    -- ── 回填标记 ────────────────────────────────────────────────────────────
    -- 【重建的事实与当场记下的事实必须分得开】。decided_at/decided_by 是真的记录,
    -- 据它重建终态是【读记录】不是【编事实】;但"完整"是假的 —— 被覆盖掉的驳回
    -- 已经没有了。所以重建行自己说自己是重建的。
    is_reconstructed    boolean NOT NULL DEFAULT false,
    reconstruction_note text,

    created_at          timestamptz NOT NULL DEFAULT now(),

    -- APR-ROUTE-1(R2):ALTER 加的列,按线上序号排在最后
    self_decided        boolean NOT NULL DEFAULT false,

    CONSTRAINT approval_log_amount_shape CHECK (
        (amount_ccy IS NULL AND currency IS NULL AND fx_rate IS NULL AND amount_base IS NULL)
        OR
        (amount_ccy IS NOT NULL AND currency IS NOT NULL AND fx_rate IS NOT NULL AND amount_base IS NOT NULL)
    ),
    CONSTRAINT approval_log_reconstruction_shape CHECK (
        NOT is_reconstructed OR reconstruction_note IS NOT NULL
    ),
    -- ★ APR-ROUTE-1(R2):自批只可能出现在报销单与医疗申报上 —— Tim 的例外只有这两类。
    --   self_approval_exception 是【规则】,这一条是【第二道保险】:哪一天别的路径
    --   让一次自批漏过来,落留痕这一行当场报错,而不是写下一行看起来正常的记录。
    -- ★ ROLE-1(Tim 的矩阵,2026-09-23):请假加进来(只对 CFO —— Tim 自己的假自己批,标记)。
    CONSTRAINT approval_log_self_decided_scope CHECK (
        NOT self_decided OR subject_type IN ('expense_claim', 'medical_claim', 'leave_request')
    )
);

CREATE INDEX idx_approval_log_subject
    ON public.approval_log (subject_type, subject_id, seq);
CREATE INDEX idx_approval_log_actor
    ON public.approval_log (actor_user_id, decided_at DESC);

-- ★★ APR-3(Tim 的 Q7):`auto_approved` 的定义【收窄】了,而这句话必须住在
--   数据库里,不只住在上面那段源码注释里 —— 一条 COMMENT ON COLUMN 是写在库里的
--   规格说明,而 `db/gate.py` 的判词二【会比它】。本刀正是被它抓到一次:
--   迁移把注释写上了线上,而镜像里没有,于是重建出来的库【整条丢失】这句定义。
--   (AGENTS.md 记着 OPS-1 那次:7 条 COMMENT ON COLUMN 只存在于线上。)
COMMENT ON COLUMN public.approval_log.decision IS
    'APR-1 建;★ APR-3(Tim 的 Q7)收窄了 auto_approved 的定义。auto_approved = 【单据生下来就是 approved】,没有任何人按过任何东西(create_purchase_order 在审批关着时就是这样)。★ 它【不】包括"一个人按了按钮,而当时审批恰好关着" —— 工单放行此前写的正是后者,note 里逐字写着「没有人做过这个决定」,而旁边就记着是谁。从 APR-3 起 release_work_order 两条分支都写 approved,与 HR 三条链、与盘点过账同一条裁定。⚠ 线上 2026-08-16 那一行 work_order / auto_approved 【没有】被改写(本表只增不改),所以这一列会同时存在两种写法,分界是一个日期不是一条规则。';

COMMENT ON TABLE public.approval_log IS
    '审批留痕,只增不改(APR-1)。谁、对什么、做了什么决定、什么时候、当时值多少。三条 HR 链保留各自的引擎但写这里;采购单等动作在 APR-2 起接入。主体是 (subject_type, subject_id) 而非可空外键 XOR —— 取舍与代价见 docs/approvals-scoping.md。';

-- ════════════════════════════════════════════════════════════════════════════
-- 只增不改的守卫。【自己报名】—— 不靠外键顺带挡(FIN-31)。
-- ════════════════════════════════════════════════════════════════════════════
-- 守卫函数体在 db/functions/guard_approval_log_append_only.sql

CREATE TRIGGER trg_approval_log_append_only
    BEFORE UPDATE OR DELETE ON public.approval_log
    FOR EACH ROW EXECUTE FUNCTION public.guard_approval_log_append_only();

ALTER TABLE public.approval_log ENABLE ROW LEVEL SECURITY;

-- 读:谁看得见留痕。审批史横跨模块,而【读它的人是要审计的人】——
-- 与 auditor 持有全部 module.*.view 是同一条思路:先给读得到相关模块的人。
-- 写:【没有 INSERT 策略】。唯一的写入口是 record_approval_decision()(属主权限),
-- 应用侧任何直接 INSERT 都会被 RLS 挡下 —— 留痕不该有第二个写法。
CREATE POLICY "approval_log select by permission"
    ON public.approval_log
    AS PERMISSIVE FOR SELECT TO authenticated
    USING (
        CASE subject_type
            WHEN 'leave_request'      THEN has_permission('module.hr.view'::text)
            WHEN 'medical_claim'      THEN has_permission('module.hr.view'::text)
            WHEN 'performance_review' THEN has_permission('module.hr.view'::text)
            WHEN 'purchase_order'     THEN has_permission('module.purchasing.view'::text)
            WHEN 'payment'            THEN has_permission('module.finance.view'::text)
            WHEN 'expense'            THEN has_permission('module.finance.view'::text)
            -- ★★ APR-3:报销单那一支 —— 这是 APR-0 §3.2 点名的第 ④ 格,
            --   也是四格里【唯一一个漏掉也不会有任何东西变红】的那一格:
            --   写得进、读不出,对每一个人都是 0 行,而且不报错。
            --   WO-1b 正是在这一格上漏了一次(APR0-WORK-ORDER-APPROVALS-INVISIBLE)。
            --   取的码与 expense_claims 自己的读策略同源(module.finance.view)——
            --   ⚠ 照直说:那张表的策略还有【或者这张单说的就是你】那一条腿,
            --   而留痕这一支【没有】给员工本人开口子。理由:一行留痕会说出
            --   "谁批的、什么级别",那是内控记录,不是自助查询;员工在 /me 上
            --   看得见自己那张单的状态,那条路没有变。
            WHEN 'expense_claim'      THEN has_permission('module.finance.view'::text)
            WHEN 'pricing_formula'    THEN has_permission('module.pricing.view'::text)
            WHEN 'stocktake'          THEN has_permission('module.stocktakes.view'::text)
            -- ★ APR-1:WO-1b 漏掉的那一支(APR0-WORK-ORDER-APPROVALS-INVISIBLE)。
            --   它写得进、读不出:线上有 1 行 work_order 留痕,而任何 authenticated
            --   身份读到的都是 0 行【而且不报错】—— 一片正确的空白,与"这张工单
            --   还没有被放行过"在屏幕上逐字相同。
            --   取的码与 work_orders 自己的读策略【同一个】:读工单的判据只该有一份定义。
            --   ⚠ 照直说:cfo 不持 module.processing.view,所以二级审批人仍然读不到它。
            WHEN 'work_order'         THEN has_permission('module.processing.view'::text)
            -- ★ PAY-REQ-1:付款申请那一支 —— 与 payment_requests 自己的读策略同一个码。
            --   漏掉它,写得进、读不出、不报错(APR-3 在报销单上记过的那一格)。
            WHEN 'payment_request'    THEN has_permission('module.finance.view'::text)
            -- ★ ROLE-1 Batch 2a:供应商那一支 —— 与 suppliers 自己的读策略同一个码。
            --   漏掉它,写得进、读不出、不报错(APR-3 记过的那一格)。
            WHEN 'supplier'           THEN has_permission('module.suppliers.view'::text)
            -- ★ PAYROLL-APR-1:工资申请那一支 —— 与 payroll_requests 自己的读策略同一个码。
            --   漏掉它,写得进、读不出、不报错(APR-3 记过的那一格)。
            WHEN 'payroll_request'    THEN has_permission('module.hr.view'::text)
            -- ★ ROLE-1 Batch 4b:收货定价申请那一支 —— 与 receipt_price_requests 自己的读策略同一对码。
            --   漏掉它,写得进、读不出、不报错(APR-3 记过的那一格)。
            WHEN 'receipt_price_request' THEN has_permission('module.inbound.view'::text)
                                          AND has_permission('data.view_purchase_prices'::text)
            -- ★ APR-5a:贷项 / 作废申请那一支 —— 与 invoice_requests 自己的读策略同一个码。
            --   漏掉它,写得进、读不出、不报错(APR-3 记过的那一格)。
            WHEN 'invoice_request'    THEN has_permission('module.finance.view'::text)
            ELSE false
        END
    );

REVOKE SELECT ON public.approval_log FROM authenticated, anon;
GRANT SELECT (id, seq, subject_type, subject_id, subject_code, decision, level,
              actor_user_id, decided_at, note, amount_ccy, currency, fx_rate,
              amount_base, is_reconstructed, reconstruction_note, created_at,
              self_decided)
    ON public.approval_log TO authenticated;

COMMENT ON COLUMN public.approval_log.self_decided IS
    'APR-ROUTE-1(Tim 的 R2):按下去的这个人,是不是这张单据的提单人或主角(按人认,经 self_leg)。★ 记的是【事实】不是【规则】:由 record_approval_decision 对 approved / rejected 两种决定计算;auto_approved 与 approval_voided 不是一次决定,恒为 false。唯一允许它为 true 的是 Tim 的例外(二级审批角色的持有人决定自己的报销单或医疗申报;ROLE-1 起加上请假),approval_log_self_decided_scope 把它钉在这三类上。自批报表 self_approved_decisions() 读它。★ 加列时线上 14 行里没有一行是"决定人 = 主角"的决定(APR-ROUTE-1 grilling 实测),所以 DEFAULT false 对历史行是真话,不是回填。';
