-- db/tables/employee_account_history.sql
-- APR-ROUTE-1 Batch B(Tim 的 Q2):额外账号的【链接与解除】,只增不改。
--
-- 【为什么要一张史表】一个账号属于谁,决定了它的哪些决定算"自批"。
-- 链接可以解除(Q2),而解除之后 account_person() 答的就是另一个答案 ——
-- 于是"那一天它属于谁"必须有地方查得到。approval_log.self_decided 记的是
-- 【做决定那一刻】的事实,解除链接不回头改它(本表与它一起,就是那一刻的证词)。
--
-- 【唯一的写入者】link_additional_account / unlink_additional_account。
-- 本表没有 INSERT 策略;UPDATE / DELETE 被守卫当场拒绝。
--
-- NOTE: introduced by db/migrations/2026-09-23-aproute1b-one-person-several-accounts-and-gm-reads.sql.

CREATE TABLE public.employee_account_history (
    id             uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    seq            bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY UNIQUE,
    action         text NOT NULL CHECK (action IN ('linked', 'unlinked')),
    user_id        uuid NOT NULL,
    employee_id    uuid NOT NULL,
    actor_user_id  uuid,
    changed_at     timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX idx_employee_account_history_user
    ON public.employee_account_history (user_id, seq);

COMMENT ON TABLE public.employee_account_history IS
    'APR-ROUTE-1 Batch B(Q2):额外账号的链接与解除,只增不改。谁、什么时候、把哪个账号链到(或解除出)哪个人。唯一写入者是 link_additional_account / unlink_additional_account。approval_log.self_decided 记的是做决定那一刻的事实,解除链接不回头改它 —— 本表就是"那一刻它属于谁"的证词。读的门 action.manage_permissions,与谁改得了它同一个码。';

CREATE TRIGGER trg_employee_account_history_append_only
    BEFORE UPDATE OR DELETE ON public.employee_account_history
    FOR EACH ROW EXECUTE FUNCTION public.guard_employee_account_history_append_only();

REVOKE ALL ON public.employee_account_history FROM anon;

ALTER TABLE public.employee_account_history ENABLE ROW LEVEL SECURITY;

CREATE POLICY "employee_account_history select by permission"
    ON public.employee_account_history
    AS PERMISSIVE FOR SELECT TO authenticated
    USING (has_permission('action.manage_permissions'::text));
